/* A escola mantém a biblioteca e o registro de estudo sob as permissões do servidor. */
window.ACADEMIA=(()=>{
 let blobURL=null;const liberarBlob=()=>{if(blobURL){URL.revokeObjectURL(blobURL);blobURL=null;}};window.addEventListener('hashchange',liberarBlob);
 const tituloTipo={video:'Vídeo',texto:'Leitura integral',documento:'Documento',nr:'Norma Regulamentadora'};
 const link=id=>'#/material/'+encodeURIComponent(id);
 const api=(operacao,args={})=>STORE.api('escola',{operacao:'academia.'+operacao,...args});
 const salvar=(operacao,args,feito)=>EDUCACAO.executar({operacao:'academia.'+operacao,...args},feito);
 const nav=()=>'<nav class="academia-nav" aria-label="Ambiente de aprendizagem">'+[['#/','Meus cursos'],['#/biblioteca','Biblioteca'],['#/videos','Vídeos'],['#/nrs','NRs'],['#/avaliacoes','Avaliações'],['#/perfil','Perfil e Desenvolvimento'],['#/conquistas','Meu histórico']].map(([u,t])=>'<a '+(location.hash===u?'aria-current="page"':'')+' href="'+u+'">'+t+'</a>').join('')+'</nav>';
 function layout(app,titulo,sub,acoes=''){EDUCACAO.conferirIdentidade();app.innerHTML=htmlTopo('conhecimento')+'<div class="miolo escola academia">'+nav()+'<header class="edu-cab"><div><div class="eyebrow">ESCOLA IMPRESILK</div><h1>'+esc(titulo)+'</h1><p>'+esc(sub)+'</p></div><div class="acoes">'+acoes+'</div></header><div id="academia-conteudo"></div></div>';ligarTopo();return $('#academia-conteudo');}
 const campo=(id,rot,valor='',extra='')=>'<div class="campo"><label for="ac-'+id+'">'+rot+'</label><input id="ac-'+id+'" '+extra+' value="'+esc(valor)+'"></div>';
 const area=(id,rot,valor='',extra='')=>'<div class="campo"><label for="ac-'+id+'">'+rot+'</label><textarea id="ac-'+id+'" '+extra+'>'+esc(valor)+'</textarea></div>';
 function resumo(m,r){return r?.versao===m.versao?(r.leituraEm?'Estudo declarado':r.abertaEm?'Em estudo':'Não iniciado'):'Não iniciado';}
 async function render(app){const hash=location.hash;layout(app,'Seu espaço de aprendizagem','Consultando os materiais liberados…');try{const data=await api('biblioteca');if(location.hash!==hash)return;
   if(ROTA.nome==='material-editor'){await editor(app,data);return;}
   if(ROTA.nome==='material'){await leitor(app,data);return;}
   biblioteca(app,data);
 }catch(e){const el=layout(app,'Não foi possível consultar a escola',e.message||'Confira a conexão e tente novamente.');el.innerHTML='<button class="botao" id="ac-retry">Tentar novamente</button>';$('#ac-retry').onclick=()=>render(app);}}
 function biblioteca(app,d){const videos=ROTA.nome==='videos';const ms=d.materiais.filter(m=>!videos||m.tipo==='video');const el=layout(app,videos?'Vídeos para aprender e aplicar':'Sua biblioteca de formação',videos?'Orientações, demonstrações e aulas para estudar dentro da escola.':'Materiais completos, com versão e registro pessoal de estudo.',d.podeGerir?'<a class="botao" href="#/material-editor/'+(videos?'novo-video':'novo')+'">'+(videos?'Cadastrar vídeo':'Adicionar material')+'</a>':'');
  el.innerHTML=(!videos?'<p class="dica"><a href="#/conhecimento">Consultar a base de conhecimento e os treinamentos existentes</a></p>':'')+'<section class="card ac-filtros">'+campo('busca','Buscar por título, assunto ou objetivo','','type="search" placeholder="O que você quer aprender?"')+'<div class="campo"><label for="ac-categoria">Assunto</label><select id="ac-categoria"><option value="">Todos os assuntos</option>'+[...new Set(ms.map(m=>m.categoria).filter(Boolean))].sort().map(c=>'<option>'+esc(c)+'</option>').join('')+'</select></div></section><p class="dica" id="ac-contagem" aria-live="polite"></p><div class="edu-grid" id="ac-grid"></div><p class="dica">Última consulta: '+fmtDataHora(d.atualizadoEm)+'. Concluir o estudo não equivale à aprovação em uma avaliação.</p>';
  const pintar=()=>{const q=norm($('#ac-busca').value),cat=$('#ac-categoria').value;const lista=ms.filter(m=>(!cat||cat===m.categoria)&&norm([m.titulo,m.objetivo,m.categoria].join(' ')).includes(q));$('#ac-contagem').textContent=lista.length+' material(is)';$('#ac-grid').innerHTML=lista.length?lista.map(m=>{const r=d.estudos.find(r=>r.materialId===m.id&&r.versao===m.versao);return '<article class="ac-card '+esc(m.tipo)+'"><div class="ac-card-marca" aria-hidden="true">'+(m.tipo==='video'?'▶':'▤')+'</div><div><span class="ac-kicker">'+esc(m.categoria||tituloTipo[m.tipo])+'</span><h2><a href="'+link(m.id)+'">'+esc(m.titulo)+'</a></h2><p>'+esc(m.objetivo)+'</p><div class="ac-meta"><span>Versão '+esc(m.versao)+'</span>'+(m.duracaoMinutos?'<span>'+m.duracaoMinutos+' min estimados</span>':'')+'</div><span class="edu-status '+(r?.leituraEm?'concluida':r?.abertaEm?'em_andamento':'nao_iniciada')+'">'+(m.publicada?resumo(m,r):'Em preparação')+'</span></div></article>';}).join(''):'<section class="card"><h2>'+ (q?'Nenhum material encontrado':'Vamos construir esta biblioteca')+'</h2><p>'+(d.podeGerir?'Cadastre os materiais e escolha quem pode estudá-los.':'Os materiais liberados para você aparecerão aqui.')+'</p></section>';};$('#ac-busca').oninput=pintar;$('#ac-categoria').onchange=pintar;pintar();
 }
 async function leitor(app,d){const {material:m}=await api('abrirMaterial',{materialId:ROTA.arg});if(ROTA.nome!=='material'||ROTA.arg!==m.id)return;let r=d.estudos.find(x=>x.materialId===m.id&&x.versao===m.versao)||{},pagina=r.pagina||1;
  const el=layout(app,m.titulo,m.objetivo,'<a class="botao mini suave" href="#/'+(m.tipo==='video'?'videos':'biblioteca')+'">← Biblioteca</a>'+(d.podeGerir?'<a class="botao mini suave" href="#/material-editor/'+encodeURIComponent(m.id)+'">Editar material</a>':''));
  el.innerHTML='<div class="ac-meta"><span>'+esc(tituloTipo[m.tipo])+'</span><span>Versão '+esc(m.versao)+'</span>'+(m.duracaoMinutos?'<span>'+m.duracaoMinutos+' min estimados</span>':'')+'</div><section class="card ac-estudo"><div class="ac-player" id="ac-player"></div><div id="ac-registro" aria-live="polite"></div></section><section class="card"><h2>Seu próximo passo</h2><p>Depois de estudar o material, retome o curso para realizar as atividades e avaliações correspondentes. Seu registro de estudo permanece separado do resultado da prova.</p><a class="botao suave" href="#/">Meus cursos e trilhas</a></section>';
  const registrar=async(evento,args={})=>{const res=await salvar('registrarMaterial',{materialId:m.id,versao:m.versao,evento,...args});if(res){r=res.registro;registroHtml();}return res;};
  function registroHtml(){$('#ac-registro').innerHTML='<div class="ac-estados"><span>'+(r.abertaEm?'✓ Material aberto em '+fmtDataHora(r.abertaEm):'○ Material ainda não aberto')+'</span><span>'+(r.leituraEm?'✓ Estudo declarado em '+fmtDataHora(r.leituraEm):'○ Estudo ainda não declarado')+'</span></div><p class="dica">Sua declaração registra o estudo desta versão. Não comprova domínio da atividade.</p>'+(d.pessoa&&!r.leituraEm?'<button class="botao" id="ac-concluir"'+(!r.abertaEm?' disabled':'')+'>Registrar estudo concluído</button>':'');if($('#ac-concluir'))$('#ac-concluir').onclick=async()=>{const bt=$('#ac-concluir');bt.disabled=true;const res=await registrar('leitura');if(!res&&bt.isConnected)bt.disabled=false;};}
  registroHtml();const player=$('#ac-player');
  if(m.tipo==='video'){
    player.innerHTML='<div class="ac-video-capa"><span aria-hidden="true">▶</span><h2>Uma pausa para aprender.</h2><p>O vídeo será carregado do YouTube quando você iniciar.</p><button class="botao" id="ac-play">Reproduzir aqui</button></div><p class="dica">Se o autor desativou a reprodução incorporada ou restringiu o vídeo, <a href="'+esc(m.url)+'" target="_blank" rel="noopener noreferrer">abrir no YouTube</a>.</p>';
    $('#ac-play').onclick=async()=>{if(d.pessoa&&!await registrar('abrir'))return;$('.ac-video-capa',player).innerHTML='<iframe class="ac-video" src="'+esc(m.embed)+'?playsinline=1" title="'+esc(m.titulo)+'" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share; fullscreen" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe>';};
  }else if(m.temPDF&&!m.paginas?.length){
    player.innerHTML='<button class="botao" id="ac-abrir-pdf">Ler documento completo</button><p class="dica">O PDF original será consultado com sua permissão de acesso.</p>';
    $('#ac-abrir-pdf').onclick=async()=>{const bt=$('#ac-abrir-pdf');bt.disabled=true;try{const pdf=await api('arquivoPDF',{materialId:m.id});if(d.pessoa&&!await registrar('abrir')){bt.disabled=false;return;}liberarBlob();const bytes=Uint8Array.from(atob(pdf.base64),c=>c.charCodeAt(0));blobURL=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));player.innerHTML='<div class="acoes"><a class="botao mini suave" target="_blank" rel="noopener" href="'+blobURL+'">Abrir em tela inteira</a><a class="botao mini suave" download="'+esc(m.titulo)+'.pdf" href="'+blobURL+'">Baixar original</a></div><iframe class="ac-documento" title="'+esc(m.titulo)+'" src="'+blobURL+'#page='+(r.pagina||1)+'"></iframe><div class="ac-leitor-toolbar"><label for="ac-pdf-pagina">Página para retomar</label><input id="ac-pdf-pagina" type="number" min="1" value="'+(r.pagina||1)+'"><button class="botao mini suave" id="ac-pdf-marcar">Salvar ponto de leitura</button></div>';$('#ac-pdf-marcar').onclick=async()=>{if(await registrar('pagina',{pagina:Number($('#ac-pdf-pagina').value)}))toast('Ponto de leitura salvo.');};}catch(e){toast(e.message,'erro');if(bt.isConnected)bt.disabled=false;}};
  }else if(m.paginas?.length){
    player.innerHTML='<div class="ac-leitor-toolbar"><button class="botao mini suave" id="ac-prev" aria-label="Página anterior">←</button><label for="ac-page">Página</label><input id="ac-page" type="number" min="1" max="'+m.paginas.length+'" value="'+pagina+'"><span>de '+m.paginas.length+'</span><button class="botao mini suave" id="ac-next" aria-label="Próxima página">→</button><button class="botao mini suave" id="ac-marcar">Salvar ponto de leitura</button></div><article class="ac-pagina" id="ac-texto" tabindex="0"></article>'+(m.temPDF?'<button class="botao mini suave" id="ac-pdf-original">Ver PDF original completo</button>':'')+(m.url?'<p><a href="'+esc(m.url)+'" target="_blank" rel="noopener noreferrer">Consultar documento original</a></p>':'');
    const pintar=()=>{$('#ac-page').value=pagina;$('#ac-texto').textContent=m.paginas[pagina-1].split('\n').map(l=>l.trim()).join('\n')||'Esta página contém elementos gráficos. Consulte o PDF original completo.';$('#ac-prev').disabled=pagina<=1;$('#ac-next').disabled=pagina>=m.paginas.length;};$('#ac-prev').onclick=()=>{pagina--;pintar();};$('#ac-next').onclick=()=>{pagina++;pintar();};$('#ac-page').onchange=()=>{pagina=Math.max(1,Math.min(m.paginas.length,Number($('#ac-page').value)||1));pintar();};$('#ac-marcar').onclick=async()=>{if(await registrar('pagina',{pagina}))toast('Ponto de leitura salvo.');};pintar();if($('#ac-pdf-original'))$('#ac-pdf-original').onclick=async()=>{const bt=$('#ac-pdf-original');bt.disabled=true;try{const pdf=await api('arquivoPDF',{materialId:m.id});liberarBlob();blobURL=URL.createObjectURL(new Blob([Uint8Array.from(atob(pdf.base64),c=>c.charCodeAt(0))],{type:'application/pdf'}));const dlg=abrirModal('<h2>'+esc(m.titulo)+'</h2><p><a class="botao mini suave" href="'+blobURL+'" target="_blank" rel="noopener">Abrir em tela inteira</a> <a class="botao mini suave" href="'+blobURL+'" download="'+esc(m.titulo)+'.pdf">Baixar original</a></p><iframe class="ac-documento" title="PDF original: '+esc(m.titulo)+'" src="'+blobURL+'#page='+pagina+'"></iframe><button class="botao suave" id="ac-fechar-original">Voltar à leitura</button>');$('#ac-fechar-original').onclick=()=>{dlg.remove();liberarBlob();};}catch(e){toast(e.message,'erro');}finally{bt.disabled=false;}};if(d.pessoa)await registrar('abrir');
  }else if(m.url){player.innerHTML='<iframe class="ac-documento" src="'+esc(m.url)+'" title="'+esc(m.titulo)+'" sandbox="allow-scripts allow-same-origin allow-popups" referrerpolicy="no-referrer"></iframe><p class="dica">Se a fonte não permite exibição interna, <a href="'+esc(m.url)+'" target="_blank" rel="noopener noreferrer">abra o documento original</a>.</p>';if(d.pessoa)await registrar('abrir');}
  else player.innerHTML='<p>O material integral ainda precisa ser preparado pela gestão.</p>';
 }
 async function editor(app,d){if(!d.podeGerir){layout(app,'Área restrita','Somente pessoas autorizadas organizam a biblioteca.');return;}const novo=ROTA.arg.startsWith('novo');const m=novo?{id:uuid(),tipo:ROTA.arg==='novo-video'?'video':ROTA.arg==='novo-nr'?'nr':'texto',titulo:'',versao:'1.0',setor:'',objetivo:'',categoria:'',publicada:false,ativa:true,liberacao:{pessoas:[],cargos:[],setores:[],todos:false}}:(await api('abrirMaterial',{materialId:ROTA.arg})).material;
  const el=layout(app,novo?'Um novo material para a escola':'Editar: '+m.titulo,'Cadastre o conteúdo completo, informe o objetivo e escolha o público.','<a class="botao mini suave" href="#/biblioteca">Voltar</a>');
  el.innerHTML='<form id="ac-editor"><section class="card"><div class="edu-form-grid">'+campo('titulo','Título',m.titulo,'required maxlength="200"')+'<div class="campo"><label for="ac-tipo">Tipo de material</label><select id="ac-tipo">'+Object.entries(tituloTipo).map(([k,v])=>'<option value="'+k+'"'+(m.tipo===k?' selected':'')+'>'+v+'</option>').join('')+'</select></div>'+campo('versao','Versão',m.versao,'required maxlength="40"')+campo('setor','Setor responsável',m.setor,'required maxlength="200"')+campo('categoria','Assunto',m.categoria,'maxlength="120"')+campo('tempo','Tempo estimado (minutos, opcional)',m.duracaoMinutos||'','type="number" min="1" max="10000"')+'</div>'+area('objetivo','Objetivo de aprendizagem',m.objetivo,'required maxlength="4000"')+'<div id="ac-fonte"></div><div id="ac-nr-config"></div><p class="dica">Para anexar um PDF, salve primeiro o material como rascunho e abra Editar material. Use somente materiais cuja utilização foi autorizada. Mudanças no conteúdo exigem nova versão para preservar os registros anteriores.</p></section><section class="card"><h2>Quem pode estudar?</h2>'+audienciaHtml(d.pessoas,m.liberacao)+'<label class="edu-check"><input id="ac-publicada" type="checkbox"'+(m.publicada?' checked':'')+'> Liberar para o público selecionado</label><label class="edu-check"><input id="ac-ativa" type="checkbox"'+(m.ativa?' checked':'')+'> Material ativo</label></section><div class="acoes"><button class="botao" type="submit">Salvar material</button><span class="dica">Salvo somente após confirmação do servidor.</span></div></form>';
  if(!novo&&m.tipo!=='video'){
    el.insertAdjacentHTML('beforeend','<section class="card"><h2>Documento original em PDF</h2><p>O arquivo fica em armazenamento privado, com acesso conforme o público deste material. Máximo de 25 MB.</p><label for="ac-arquivo">Selecionar PDF original</label><input id="ac-arquivo" type="file" accept="application/pdf,.pdf"><button class="botao suave" id="ac-enviar-pdf">Enviar PDF original</button><p id="ac-upload-estado" role="status"></p></section>');
    $('#ac-enviar-pdf').onclick=async()=>{const file=$('#ac-arquivo').files[0];if(!file){toast('Selecione um PDF.','erro');return;}if(file.size>25000000){toast('O PDF deve ter até 25 MB.','erro');return;}const bt=$('#ac-enviar-pdf');bt.disabled=true;$('#ac-upload-estado').textContent='Preparando envio protegido…';try{const bytes=new Uint8Array(await file.arrayBuffer());let bin='';for(let n=0;n<bytes.length;n+=8192)bin+=String.fromCharCode(...bytes.subarray(n,n+8192));const r=await salvar('enviarPDF',{materialId:m.id,versao:m.versao,base64:btoa(bin),expectedRevision:m._serverRevision||0},()=>{toast('PDF confirmado no servidor.');location.hash=link(m.id);});if(!r){$('#ac-upload-estado').textContent='Envio ainda não confirmado. Confira a mensagem e tente novamente.';bt.disabled=false;}}catch(e){$('#ac-upload-estado').textContent=e.message;bt.disabled=false;}};
  }
  let url=m.url||'',paginas=(m.paginas||[]).join('\n\n---PÁGINA---\n\n');const fonte=()=>{$('#ac-fonte').innerHTML=campo('url',$('#ac-tipo').value==='video'?'Link do YouTube':'Link do documento original (opcional)',url,'type="url" '+($('#ac-tipo').value==='video'?'required':'')+' placeholder="https://…"')+($('#ac-tipo').value!=='video'?area('paginas','Material integral — separe as páginas com ---PÁGINA---',paginas,'class="ac-texto-editor"'):'<p class="dica">Cole o link do vídeo. Não é necessário copiar código de incorporação. O vídeo permanece hospedado no YouTube.</p>');$('#ac-url').oninput=e=>url=e.target.value;if($('#ac-paginas'))$('#ac-paginas').oninput=e=>paginas=e.target.value;};const nrCampos=()=>{$('#ac-nr-config').innerHTML=$('#ac-tipo').value==='nr'?'<h2>Configuração pelo responsável da NR</h2><div class="edu-form-grid">'+campo('nr-numero','Número da NR',m.nr?.numero||'','required pattern="[0-9]{1,2}"')+campo('nr-versao','Versão oficial consultada',m.nr?.versaoOficial||'','required')+campo('nr-fonte','Fonte oficial do Ministério do Trabalho',m.nr?.fonte||'','required type="url"')+campo('nr-validade','Validade em meses (somente quando definida)',m.nr?.validadeMeses||'','type="number" min="1" max="120"')+'</div>'+area('nr-publico','Público e aplicabilidade definidos pelo responsável',m.nr?.publico||'','required')+'<div class="campo"><label for="ac-nr-responsavel">Responsável pela capacitação</label><select id="ac-nr-responsavel" required><option value="">Selecione</option>'+d.pessoas.filter(p=>p.usuario).map(p=>'<option value="'+esc(p.usuario)+'"'+(m.nr?.responsavel===p.usuario?' selected':'')+'>'+esc(p.nome)+'</option>').join('')+'</select></div>'+area('nr-requisitos','Requisitos para concluir — um por linha',m.nr?.requisitos?.join('\n')||'','required')+'<p class="dica">Configure com base na norma vigente e na orientação do responsável. O responsável também precisa de permissão de gestão ou de instrutor neste setor. O sistema não presume carga horária, validade ou habilitação profissional.</p>':'';};$('#ac-tipo').onchange=()=>{fonte();nrCampos();};fonte();nrCampos();
  $('#ac-editor').onsubmit=async ev=>{ev.preventDefault();const bt=ev.target.querySelector('button[type=submit]');bt.disabled=true;const material={...m,titulo:$('#ac-titulo').value.trim(),tipo:$('#ac-tipo').value,versao:$('#ac-versao').value.trim(),setor:$('#ac-setor').value.trim(),categoria:$('#ac-categoria').value.trim(),objetivo:$('#ac-objetivo').value.trim(),duracaoMinutos:$('#ac-tempo').value?Number($('#ac-tempo').value):null,url:url.trim(),paginas:paginas?paginas.split(/\s*---PÁGINA---\s*/):[],publicada:$('#ac-publicada').checked,ativa:$('#ac-ativa').checked,liberacao:lerAudiencia()};if(material.tipo==='nr')material.nr={numero:$('#ac-nr-numero').value,versaoOficial:$('#ac-nr-versao').value,fonte:$('#ac-nr-fonte').value,publico:$('#ac-nr-publico').value,responsavel:$('#ac-nr-responsavel').value,requisitos:$('#ac-nr-requisitos').value.split('\n').map(x=>x.trim()).filter(Boolean),validadeMeses:$('#ac-nr-validade').value?Number($('#ac-nr-validade').value):null};const res=await salvar('salvarMaterial',{material,expectedRevision:m._serverRevision||0},()=>{location.hash=link(m.id);});if(!res)bt.disabled=false;};
 }
 function audienciaHtml(ps,l={}){return '<div class="edu-form-grid">'+[['pessoas','Pessoas do RH',ps.map(p=>[p.colaboradorId,p.nome])],['cargos','Funções do RH',[...new Map(ps.filter(p=>p.cargoId).map(p=>[p.cargoId,p.funcao||p.cargoId]))]],['setores','Setores',[...new Set(ps.map(p=>p.setor||p.area).filter(Boolean))].map(s=>[s,s])]].map(([k,t,opts])=>'<div class="campo"><label for="ac-'+k+'">'+t+'</label><select id="ac-'+k+'" multiple size="4">'+opts.map(([v,n])=>'<option value="'+esc(v)+'"'+((l[k]||[]).includes(v)?' selected':'')+'>'+esc(n)+'</option>').join('')+'</select></div>').join('')+'</div>'+(souAdmin()?'<label class="edu-check"><input id="ac-todos" type="checkbox"'+(l.todos?' checked':'')+'> Todas as pessoas vinculadas ao RH</label>':'');}
 function lerAudiencia(){return Object.fromEntries(['pessoas','cargos','setores'].map(k=>[k,Array.from($('#ac-'+k).selectedOptions).map(o=>o.value)]).concat([['todos',!!$('#ac-todos')?.checked]]));}
 return {render,api,salvar,nav,layout,campo,area,audienciaHtml,lerAudiencia};
})();
