/* Escola interna: operações confirmadas pelo servidor, identidade derivada do RH.
   O catálogo operacional legado continua no STORE; avaliações nunca são upserts livres. */
window.EDUCACAO = (() => {
  const estados={nao_iniciada:'Não iniciada',em_andamento:'Em andamento',aguardando_validacao:'Aguardando validação',concluida:'Concluída',revisar:'Revisão necessária'};
  const tipos={cultura:'Conhecer a Impresilk',etica:'Código de Ética e Conduta',caderno:'Caderno da função',pop:'POPs da função',pratica:'Prática acompanhada',avaliacao:'Avaliação e conclusão',continua:'Educação contínua'};
  let snapshot=null, identidade='', carregando=null, erro='', mutacao=null, enviando=false, seq=0;
  const rota=(id,etapa)=>'#/formacao/'+encodeURIComponent(id)+(etapa?'/'+encodeURIComponent(etapa):'');
  const pessoaKey=()=>[SESSAO?.usuario,SESSAO?.papel,SESSAO?.pessoaRH?.colaboradorId].join('|');
  function pendenciaKey(){return 'educacao_envio_v1_'+encodeURIComponent(pessoaKey());}
  function zerar(){snapshot=null;erro='';mutacao=null;enviando=false;carregando=null;seq++;identidade=pessoaKey();try{if(typeof sessionStorage!=='undefined')mutacao=JSON.parse(sessionStorage.getItem(pendenciaKey()) || 'null');}catch{erro='Não foi possível recuperar o envio deste aparelho. Confira o histórico antes de responder novamente.';}}
  function estadoEnvio(){return {pendente:!!mutacao,enviando,erro,consultando:!!carregando};}
  function podeAcompanhar(){return !!(snapshot?.gestao?.podeGerir || snapshot?.gestao?.podeValidar);}
  function notificarEstado(){if(typeof window.dispatchEvent==='function' && typeof CustomEvent!=='undefined')window.dispatchEvent(new CustomEvent('educacao:estado'));}
  async function conferirEstado(){if(mutacao && !enviando)return executar(mutacao,()=>render($('#app')));snapshot=null;await carregar();if(['inicio','formacao','formacao-editor','conquistas','escola'].includes(ROTA.nome) && ROTA.nome!=='formacao-editor')await render($('#app'));else if(erro)toast(erro,'erro');}
  function guardarEnvio(envio){if(typeof sessionStorage==='undefined')return;sessionStorage.setItem(pendenciaKey(),JSON.stringify(envio));}
  function limparEnvio(){try{if(typeof sessionStorage!=='undefined')sessionStorage.removeItem(pendenciaKey());}catch{/* Identificador persistido será reenviado sem duplicar a atividade. */}}
  if(typeof window.addEventListener==='function')window.addEventListener('beforeunload',ev=>{if(mutacao){ev.preventDefault();ev.returnValue='';}});

  function status(e,p){return e?.status || p?.status || 'nao_iniciada';}
  function progresso(f,p){if(f.progresso)return f.progresso;const es=(f.etapas || []).filter(e=>e.obrigatoria!==false),concluidas=es.filter(e=>status(e,p?.etapas?.[e.id])==='concluida').length;return {total:es.length,concluidas,percentual:es.length?Math.round(concluidas/es.length*100):0};}
  function bloqueio(f,e,p){
    if(e.motivoBloqueio)return e.motivoBloqueio;
    const faltam=(e.prerequisitos || []).filter(id=>p?.etapas?.[id]?.status!=='concluida');
    if(faltam.length)return 'Conclua antes: '+faltam.map(id=>f.etapas.find(x=>x.id===id)?.titulo || id).join(', ')+'.';
    if(e.preparacaoPendente || e.statusFonte==='pendente')return 'Conteúdo em preparação pela gestão.';
    return '';
  }
  const meuProgresso=f=> (snapshot?.aprendizagem || []).find(p=>p.formacaoId===f.id) || {etapas:{},pontos:0,conquistas:[],historico:[]};
  function proxima(f,p){return (f.etapas || []).find(e=>e.obrigatoria!==false && status(e,p.etapas?.[e.id])!=='concluida') || (f.etapas || []).find(e=>status(e,p.etapas?.[e.id])!=='concluida');}
  function selo(st){return '<span class="edu-status '+esc(st)+'">'+esc(estados[st] || st)+'</span>';}
  function header(aba='inicio'){return htmlTopo(aba)+'<div class="miolo escola">';}
  function intro(titulo,sub,acoes=''){return '<header class="edu-cab"><div><div class="eyebrow">EDUCAÇÃO IMPRESILK</div><h1>'+esc(titulo)+'</h1><p>'+esc(sub)+'</p></div><div class="acoes">'+acoes+'</div></header>';}
  function aviso(){return (erro?'<div class="aviso amarelo" role="alert">'+esc(erro)+' <button class="botao mini suave" id="edu-recarregar">Tentar novamente</button></div>':'')+(mutacao?'<div class="aviso amarelo" role="alert">A confirmação ainda não chegou. Sua atividade continua nesta tela. <button class="botao mini suave" id="edu-reenviar">Conferir envio</button></div>':'');}
  function fim(app){app.insertAdjacentHTML('beforeend','');ligarTopo();$$('[data-scroll]').forEach(a=>a.onclick=ev=>{ev.preventDefault();document.getElementById(a.dataset.scroll)?.scrollIntoView({behavior:'smooth'});});const bt=$('#edu-recarregar');if(bt)bt.onclick=()=>{snapshot=null;render(app);};const re=$('#edu-reenviar');if(re)re.onclick=()=>executar(mutacao,()=>{snapshot=null;render(app);});}
  async function carregar(){
    if(identidade!==pessoaKey())zerar();
    if(carregando)return carregando;
    const ciclo=seq,conta=pessoaKey();
    carregando=STORE.api('escola',{operacao:'painel'}).then(r=>{if(ciclo!==seq || conta!==pessoaKey())return; if(r?.ok!==true || !Array.isArray(r.formacoes) || !Array.isArray(r.aprendizagem))throw new Error('A consulta da escola não foi confirmada pelo servidor. Tente novamente.');snapshot=r;erro='';}).catch(e=>{if(ciclo===seq)erro=e.message || 'Não foi possível consultar a escola. Tente novamente.';}).finally(()=>{if(ciclo===seq){carregando=null;notificarEstado();}});
    notificarEstado();return carregando;
  }
  async function executar(payload,feito){
    if(enviando)return null;
    if(mutacao && payload!==mutacao){toast('Confira o envio anterior antes de iniciar outra atividade.','erro');return;}
    const envio=payload.mutationId?payload:{...payload,mutationId:uuid()}, conta=pessoaKey();
    try{guardarEnvio(envio);}catch{erro='Não foi possível preservar este envio no aparelho. Nenhuma atividade foi enviada. Mantenha o formulário aberto, libere espaço e tente novamente.';mostrarFalha();notificarEstado();return null;}mutacao=envio;enviando=true;notificarEstado();
    try{
      const r=await STORE.api('escola',envio);
      if(r?.ok!==true)throw new Error('O servidor não confirmou a gravação. Confira o envio antes de continuar.');
      if(conta!==pessoaKey()){zerar();return;}
      mutacao=null;limparEnvio();erro='';snapshot=null;enviando=false;notificarEstado();
      if(feito){try{await feito(r);}catch{erro='Registro confirmado no servidor. Não foi possível atualizar a visualização; tente consultar novamente.';mostrarFalha();}}
      return r;
    }catch(e){
      if(conta!==pessoaKey()){zerar();return;}
      // Erro de validação é resposta definitiva; falha de rede mantém o mesmo identificador.
      if(e.status && e.status>=400 && e.status<500 && ![408,429].includes(e.status)){mutacao=null;limparEnvio();}
      erro=e.message || 'Envio sem confirmação. Tente novamente com esta tela aberta.';
      toast(erro,'erro');mostrarFalha();return null;
    }finally{enviando=false;notificarEstado();
    }
  }
  function mostrarFalha(){
    const main=$('.escola');if(!main)return;
    let box=$('#edu-envio-estado');if(!box){box=document.createElement('div');box.id='edu-envio-estado';box.className='aviso amarelo';box.setAttribute('role','alert');main.prepend(box);}
    box.innerHTML=esc(erro)+(mutacao?' <button class="botao mini suave" id="edu-retentar-envio">Conferir envio</button>':' <button class="botao mini suave" id="edu-reconsultar">Consultar novamente</button>');
    const retry=$('#edu-retentar-envio');if(retry)retry.onclick=async()=>{retry.disabled=true;const r=await executar(mutacao,()=>{snapshot=null;render($('#app'));});if(!r&&retry.isConnected)retry.disabled=false;};
    const reload=$('#edu-reconsultar');if(reload)reload.onclick=()=>{snapshot=null;render($('#app'));};
  }
  async function atualizarEtapa(app,fid,eid){await carregar();if(!snapshot){erro='Registro confirmado no servidor. A consulta atualizada está indisponível; tente novamente.';mostrarFalha();return;}const f=snapshot.formacoes.find(x=>x.id===fid),e=f?.etapas?.find(x=>x.id===eid);if(f&&e)etapa(app,f,e);else render(app);}
  function cartao(f){const p=meuProgresso(f),pr=progresso(f,p),e=proxima(f,p);return '<article class="edu-jornada"><div class="edu-card-top"><span class="edu-marca" aria-hidden="true">'+(pr.percentual===100?'✓':'↗')+'</span><h2>'+esc(f.titulo)+'</h2></div><div class="edu-progresso"><progress max="100" value="'+pr.percentual+'" aria-label="Progresso de '+esc(f.titulo)+'"></progress><b>'+pr.percentual+'%</b></div><p class="dica">'+pr.concluidas+' de '+pr.total+' etapas obrigatórias concluídas</p><p class="edu-atual">'+(e?'Etapa atual: '+esc(e.titulo):'Jornada concluída')+'</p><a class="botao mini" href="'+rota(f.id)+'">'+(e?'Continuar':'Consultar jornada')+'</a></article>';}
  function inicio(app){
    const fs=snapshot.formacoes || [],pessoa=snapshot.pessoa;
    const liberadas=fs.filter(f=>f.publicada && f.ativa!==false && f.liberada!==false);
    const ordenadas=liberadas.slice().sort((a,b)=>String(meuProgresso(b).atualizadoEm || '').localeCompare(String(meuProgresso(a).atualizadoEm || '')));
    const ativa=ordenadas.find(f=>progresso(f,meuProgresso(f)).percentual<100) || liberadas[0];
    const p=ativa?meuProgresso(ativa):null,e=ativa?proxima(ativa,p):null;
    const conquistas=(snapshot.aprendizagem || []).flatMap(p=>p.conquistas || []),pontos=(snapshot.aprendizagem || []).reduce((s,p)=>s+(p.pontos || 0),0);
    app.innerHTML=header()+intro('Seu aprendizado, passo a passo.',pessoa?((pessoa.nome || SESSAO.nome)+' · '+(pessoa.funcao || 'Função a conferir')+(pessoa.setor?' · '+pessoa.setor:'')):'Vamos organizar sua formação.',snapshot.gestao?.podeGerir?'<a class="botao suave mini" href="#/escola">Gerenciar escola</a>':'')+aviso()+
      (!pessoa?'<div class="aviso amarelo"><b>Vínculo com o RH pendente.</b> A gestão precisa conferir sua conta para liberar e registrar sua formação. A biblioteca continua disponível.</div>':'')+
      '<section class="edu-proximo"><div><div class="eyebrow">SEU PRÓXIMO PASSO</div><h2>'+esc(e?.titulo || (ativa?'Sua jornada está em dia':'Sua jornada começa aqui'))+'</h2><p>'+esc(e?bloqueio(ativa,e,p) || 'Aprenda, pratique e avance com segurança.':ativa?'Você pode rever seus conteúdos e acompanhar novas formações.':'As jornadas liberadas pela gestão aparecerão abaixo.')+'</p></div>'+(ativa?'<a class="botao" href="'+(e?rota(ativa.id,e.id):rota(ativa.id))+'">Continuar de onde parei →</a>':'<a class="botao" href="#/meus">Consultar atribuições</a>')+'</section>'+
      '<div class="edu-resumo"><span><strong>'+liberadas.length+'</strong> jornadas liberadas</span><span><strong>'+pontos+'</strong> pontos de aprendizagem</span><a href="#/conquistas"><strong>'+conquistas.length+'</strong> conquistas pessoais →</a></div>'+
      '<section aria-labelledby="edu-minhas"><div class="secao-titulo"><h2 id="edu-minhas">Minhas jornadas</h2><span class="dica">No seu ritmo, com qualidade.</span></div><div class="edu-grid">'+(liberadas.length?liberadas.map(cartao).join(''):'<div class="card edu-vazio"><h3>Nenhuma jornada liberada ainda</h3><p>A gestão pode atribuir sua formação por função, setor ou individualmente.</p></div>')+'</div></section>'+
      '<nav class="edu-atalhos" aria-label="Consulta no trabalho"><a href="#/meus">☑ Atribuições anteriores</a><a href="#/pops">▤ POPs para consultar</a><a href="#/conhecimento">◈ Conhecimento e treinamentos</a><a href="#/fab">↗ Fabricação</a></nav>'+referencias(liberadas)+'<p class="dica edu-rodape">'+(snapshot.atualizadoEm?'Consultado em '+fmtDataHora(snapshot.atualizadoEm)+'. ':'')+'Pontos reconhecem aprendizagem. A autorização para executar uma atividade depende da validação responsável.</p></div>';
    fim(app);
  }
  function referencias(fs){const refs=fs.flatMap(f=>(f.etapas || []).filter(e=>['etica','caderno'].includes(e.tipo)).map(e=>({f,e})));return refs.length?'<section class="edu-referencias"><h2>Suas referências de trabalho</h2><div class="edu-atalhos">'+refs.slice(0,6).map(({f,e})=>'<a href="'+rota(f.id,e.id)+'">'+esc(e.titulo)+'</a>').join('')+'</div></section>':'';}
  function jornada(app,f){const p=meuProgresso(f),pr=progresso(f,p);app.innerHTML=header()+intro(f.titulo,'Sua formação · versão '+f.versao,'<a class="botao suave mini" href="#/">← Minhas jornadas</a>')+aviso()+
    '<div class="edu-resumo"><span><strong>'+pr.percentual+'%</strong> concluído</span><span>'+pr.concluidas+'/'+pr.total+' etapas obrigatórias</span><a href="#/conquistas">'+(p.pontos || 0)+' pontos · conquistas →</a></div><div class="edu-grid etapas">'+(f.etapas || []).map((e,i)=>{const st=status(e,p.etapas?.[e.id]),bloq=bloqueio(f,e,p);return '<article class="edu-etapa '+esc(st)+'"><span class="edu-numero">'+String(i+1).padStart(2,'0')+'</span><h2>'+esc(e.titulo)+'</h2>'+selo(st)+'<p class="dica">'+(e.obrigatoria===false?'Complementar':'Obrigatória')+(e.duracaoMinutos?' · '+e.duracaoMinutos+' min estimados':'')+'</p>'+(bloq?'<p class="edu-bloqueio">🔒 '+esc(bloq)+'</p>':'')+'<a class="botao mini '+(bloq?'suave':'')+'" href="'+rota(f.id,e.id)+'">'+(st==='concluida'?'Rever etapa':bloq?'Ver orientações':'Abrir etapa')+'</a></article>';}).join('')+'</div><details class="card"><summary>Como avançar e ganhar pontos</summary><p>As etapas obrigatórias formam sua jornada. Cada uma mostra o critério para avançar. Ler não comprova domínio; responder e demonstrar na prática são registros separados.</p><ul>'+(f.etapas || []).map(e=>'<li>'+esc(e.titulo)+': '+Number(e.pontos || 0)+' pontos ao cumprir o critério. Novas aberturas e envios repetidos não somam pontos.</li>').join('')+'</ul></details></div>';fim(app);}
  function fonteHtml(e){return (e.fontes || []).map(f=>{const col=f.tipo==='pop'?'pops':'treinamentos',r=STORE.um(col,f.refId);return '<a class="edu-material" href="'+(f.tipo==='pop'?'#/pop/':'#/treinamento/')+encodeURIComponent(f.refId)+'">▤ '+esc(r?.titulo || f.refId)+' <small>Versão '+esc(f.versao)+'</small></a>';}).join('')+(e.documentos || []).filter(d=>window.POPS_TREINAMENTOS.urlSegura(d.url)).map(d=>'<a class="edu-material" href="'+esc(d.url)+'" target="_blank" rel="noopener noreferrer">↗ '+esc(d.titulo)+' <small>Versão '+esc(d.versao)+' · abre em outra aba</small></a>').join('');}
  function etapa(app,f,e){
    const p=meuProgresso(f),r=(p.formacaoVersao && p.formacaoVersao!==f.versao?{}:p.etapas?.[e.id]) || {},st=status(e,r),bloq=bloqueio(f,e,p),c=e.conteudo || {};
    app.innerHTML=header()+intro(e.titulo,f.titulo+' · '+(e.obrigatoria===false?'Complementar':'Obrigatória'),'<a class="botao suave mini" href="'+rota(f.id)+'">← Jornada</a>')+aviso()+
      '<div class="edu-resumo">'+selo(st)+'<span>'+Number(e.pontos || 0)+' pontos ao cumprir esta etapa</span>'+(e.duracaoMinutos?'<span>'+e.duracaoMinutos+' min estimados</span>':'')+'</div>'+(bloq?'<div class="aviso amarelo">🔒 '+esc(bloq)+'</div>':'')+
      '<div class="edu-conteudo"><section class="card"><h2>Vamos aprender</h2>'+[['aprender','O que vou aprender?'],['importancia','Por que isso importa?'],['comoFazer','Como fazer corretamente?'],['erros','Quais erros evitar?'],['evidencia','Como demonstrar que aprendi?']].map(([k,t])=>'<div class="edu-topico"><h3>'+t+'</h3><p>'+esc(c[k] || 'Conteúdo aguardando preparação pela gestão.').replace(/\n/g,'<br>')+'</p></div>').join('')+fonteHtml(e)+'</section><aside class="card edu-comprovar"><h2>Seu registro nesta etapa</h2><ul class="edu-registros"><li>'+ (r.abertaEm?'✓ Aberta em '+fmtDataHora(r.abertaEm):'○ Abertura ainda não registrada')+'</li><li>'+(r.leituraEm?'✓ Leitura registrada em '+fmtDataHora(r.leituraEm):'○ Leitura não registrada')+'</li><li>'+(r.cienciaEm?'✓ Ciência registrada em '+fmtDataHora(r.cienciaEm):e.tipo==='etica'?'○ Ciência do Código pendente':'')+'</li><li>'+(r.concluidaEm?'✓ Critério concluído em '+fmtDataHora(r.concluidaEm):'○ Critério de conclusão pendente')+'</li></ul><p class="dica">'+esc(criterio(e))+'</p>'+
      '<div id="edu-retorno" role="status" aria-live="polite"></div>'+
      (!bloq && st!=='concluida'?'<div class="edu-acoes"><button class="botao suave" data-evento="abrir">Registrar abertura</button><button class="botao suave" data-evento="leitura">Registrar leitura</button>'+(e.tipo==='etica'?'<label class="edu-check"><input type="checkbox" id="edu-ciencia"> Li o Código de Ética desta versão e registro minha ciência.</label><button class="botao" data-evento="ciencia">Registrar ciência</button>':'')+'</div>':'')+
      (r.validacao?'<div class="aviso amarelo">Retorno do responsável: '+esc(r.validacao.feedback || '')+'</div>':'')+'</aside></div>'+
      (!bloq && (e.quiz || []).length?quizHtml(e,r):'')+
      (!bloq && e.tipo==='pratica'?'<form id="edu-pratica" class="card"><h2>Prática acompanhada</h2><p>Execute com orientação do responsável. Sua evidência será analisada antes da conclusão.</p>'+(e.checklist || []).map((x,i)=>'<label class="edu-check"><input type="checkbox" name="item-'+i+'" required> '+esc(x)+'</label>').join('')+'<div class="campo"><label for="edu-evidencia">O que foi realizado? Registre o resultado e as observações do acompanhamento.</label><textarea id="edu-evidencia" required maxlength="4000">'+esc(r.evidencia || '')+'</textarea></div><button class="botao"'+(st==='aguardando_validacao' || st==='concluida'?' disabled':'')+'>Enviar para validação</button></form>':'')+
      '<details class="card"><summary>Histórico e tentativas desta etapa</summary>'+tentativasHtml(r)+'<p class="dica">As tentativas anteriores permanecem registradas. Nova versão não apaga seu histórico.</p></details>'+ (st==='concluida' && f.etapas.indexOf(e)<f.etapas.length-1?'<a class="botao" href="'+rota(f.id,f.etapas[f.etapas.indexOf(e)+1].id)+'">Próxima etapa →</a>':'')+'</div>';
    fim(app);
    $$('[data-evento]').forEach(bt=>bt.onclick=async()=>{
      if(bt.dataset.evento==='ciencia' && !$('#edu-ciencia')?.checked){toast('Confirme a ciência do Código antes de registrar.','erro');return;}
      bt.disabled=true;const res=await executar({operacao:'registrar',formacaoId:f.id,etapaId:e.id,evento:bt.dataset.evento,formacaoVersao:f.versao,aceite:bt.dataset.evento==='ciencia'},async()=>{await atualizarEtapa(app,f.id,e.id);toast('Registro confirmado pelo servidor.');});if(!res && bt.isConnected)bt.disabled=false;
    });
    const q=$('#edu-quiz');if(q)q.onsubmit=async ev=>{ev.preventDefault();const respostas={};for(const questao of e.quiz)respostas[questao.id]=Number(new FormData(q).get(questao.id));const bt=q.querySelector('button');bt.disabled=true;const res=await executar({operacao:'registrar',formacaoId:f.id,etapaId:e.id,evento:'responder',respostas,formacaoVersao:f.versao},async r=>{await atualizarEtapa(app,f.id,e.id);mostrarFeedback(r);});if(!res && bt.isConnected)bt.disabled=false;};
    const pratica=$('#edu-pratica');if(pratica)pratica.onsubmit=async ev=>{ev.preventDefault();const bt=pratica.querySelector('button');bt.disabled=true;const res=await executar({operacao:'registrar',formacaoId:f.id,etapaId:e.id,evento:'enviarPratica',formacaoVersao:f.versao,evidencia:$('#edu-evidencia').value.trim(),checklist:(e.checklist || []).map(()=>true)},async()=>{await atualizarEtapa(app,f.id,e.id);toast('Prática enviada. Aguarde o retorno do responsável.');});if(!res && bt.isConnected)bt.disabled=false;};
  }
  function criterio(e){return e.tipo==='pratica'?'Para avançar: execute o checklist e receba a validação do responsável.':e.tipo==='etica'?'Para avançar: registre leitura, ciência e demonstre compreensão na avaliação.':(e.quiz || []).length?'Para avançar: registre a leitura e alcance '+(e.minimoAcerto ?? 70)+'% na avaliação. Até '+(e.maxTentativas || 3)+' tentativas nesta versão.':'Para avançar: registre a leitura do conteúdo oficial. Isso comprova leitura, sem autorizar execução prática.';}
  function quizHtml(e,r){const n=(r.tentativas || []).length,max=e.maxTentativas || 3;return '<form class="card edu-quiz" id="edu-quiz"><h2>Demonstrar compreensão</h2><p>'+n+' de '+max+' tentativas · mínimo '+(e.minimoAcerto ?? 70)+'%</p>'+(e.quiz || []).map((q,i)=>'<fieldset><legend>'+(i+1)+'. '+esc(q.pergunta)+'</legend>'+q.opcoes.map((o,j)=>'<label class="edu-check"><input type="radio" required name="'+esc(q.id)+'" value="'+j+'"> '+esc(o)+'</label>').join('')+'</fieldset>').join('')+'<button class="botao"'+(n>=max || r.status==='concluida'?' disabled':'')+'>Conferir respostas</button>'+(n>=max && r.status!=='concluida'?'<p class="aviso amarelo">Limite de tentativas atingido. Procure o responsável para rever o conteúdo e planejar uma nova tentativa.</p>':'')+'</form>';}
  function tentativasHtml(r){return (r.tentativas || []).length?(r.tentativas || []).map((t,i)=>'<div class="edu-tentativa"><strong>Tentativa '+(i+1)+'</strong> · '+esc(t.nota ?? t.percentual ?? '—')+'% · '+fmtDataHora(t.em)+(t.feedback?'<p>'+esc(typeof t.feedback==='string'?t.feedback:(t.feedback.questoes || []).map(q=>(q.acertou?'Correta. ':'Rever. ')+q.explicacao+(q.revisar?' Revisar: '+q.revisar:'')).join('\n'))+'</p>':'')+'</div>').join(''):'<p>Nenhuma tentativa registrada.</p>';}
  function mostrarFeedback(r){const area=$('#edu-retorno');if(!area)return;const fs=r.feedback?.questoes || (Array.isArray(r.feedback)?r.feedback:r.feedback?[r.feedback]:[]);area.innerHTML='<h3>Seu resultado'+(r.feedback?.nota!=null?' · '+r.feedback.nota+'%':'')+'</h3>'+fs.map(f=>'<p>'+esc(typeof f==='string'?f:f.explicacao || f.mensagem || '')+'</p>'+(f.revisar?'<p class="dica">Revisar: '+esc(f.revisar)+'</p>':'')).join('')+(fs.length?'':'<p>Resposta registrada. Consulte o resultado e o histórico desta etapa.</p>');area.scrollIntoView({block:'center',behavior:'smooth'});}
  function conquistas(app){const ps=snapshot.aprendizagem || [];app.innerHTML=header()+intro('Sua evolução merece ser vista.','Conquistas pessoais, com o caminho que você percorreu.','<a class="botao suave mini" href="#/">← Minhas jornadas</a>')+aviso()+'<div class="edu-grid">'+(ps.flatMap(p=>(p.conquistas || []).map(c=>'<article class="edu-jornada"><span class="edu-marca" aria-hidden="true">✦</span><h2>'+esc(c.titulo || c.nome || 'Marco concluído')+'</h2><p>'+esc(snapshot.formacoes.find(f=>f.id===p.formacaoId)?.titulo || p.formacaoId)+'</p><p class="dica">'+fmtDataHora(c.em || c.conquistadaEm)+'</p></article>')).join('') || '<section class="card"><h2>Seu próximo marco está à frente</h2><p>As conquistas aparecem quando você conclui as atividades e cumpre os critérios de aprendizagem.</p></section>')+'</div><section class="card"><h2>Histórico pessoal</h2>'+ps.map(p=>'<details><summary>'+esc(snapshot.formacoes.find(f=>f.id===p.formacaoId)?.titulo || p.formacaoId)+' · '+(p.pontos || 0)+' pontos</summary>'+historicoHtml(p)+'</details>').join('')+'<p class="dica">Os pontos não substituem uma validação prática nem autorizam automaticamente o exercício de uma atividade.</p></section></div>';fim(app);}
  function historicoHtml(p){return '<ul class="edu-historico">'+[...(p.historico || []),...(p.eventos || [])].map(h=>'<li><b>'+esc(h.motivo || h.evento || h.tipo || 'Registro')+'</b> · '+fmtDataHora(h.em || h.encerradaEm)+'<span>'+esc(h.etapaId || h.motivo || '')+(h.formacaoVersao || h.versao?' · versão '+esc(h.formacaoVersao || h.versao):'')+'</span></li>').join('')+'</ul>';}
  async function render(app){
    if(typeof atualizarIdentidadeRH==='function' && !SESSAO?.identidadeConferida)await atualizarIdentidadeRH();
    if(identidade!==pessoaKey())zerar();
    const alvo=location.hash,conta=pessoaKey();
    if(!snapshot){app.innerHTML=header()+intro('Sua formação começa por você.','Consultando jornadas e registros confirmados…')+aviso()+'</div>';ligarTopo();await carregar();if(alvo!==location.hash || conta!==pessoaKey())return;if(!snapshot){app.innerHTML=header()+intro('Vamos retomar seu aprendizado.','A consulta da escola precisa de conexão. Os POPs sincronizados continuam disponíveis.')+aviso()+'<a class="botao suave" href="#/pops">Consultar POPs</a></div>';fim(app);return;}}
    if(ROTA.nome==='escola'){gestao(app);return;}
    if(ROTA.nome==='formacao-editor'){editor(app);return;}
    if(ROTA.nome==='conquistas'){conquistas(app);return;}
    if(ROTA.nome==='formacao'){const [id,eid]=ROTA.arg.split('~'),f=snapshot.formacoes.find(f=>f.id===id);if(!f){app.innerHTML=header()+intro('Jornada não disponível','Confira as formações liberadas para sua conta.')+'<a href="#/">Voltar às minhas jornadas</a></div>';fim(app);return;}const e=f.etapas?.find(e=>e.id===eid);if(e)etapa(app,f,e);else jornada(app,f);return;}
    inicio(app);
  }
  function gestao(app){
    const g=snapshot.gestao || {};
    if(!g.podeGerir && !g.podeValidar){app.innerHTML=header()+intro('Área restrita','A gestão e os responsáveis acompanham as formações conforme sua permissão.')+'</div>';fim(app);return;}
    const fs=snapshot.formacoes || [],registros=g.registros || [];
    const aIniciar=g.podeGerir?fs.filter(f=>f.publicada && f.ativa!==false).flatMap(f=>(g.pessoas || []).filter(p=>{
      const pid=p.colaboradorId || String(p.id || '').replace(/^p-/,''),lib=f.liberacao || {};
      const atribuida=Array.isArray(f.pessoasLiberadas)?f.pessoasLiberadas.includes(pid):pid && (lib.todos===true || (lib.pessoas || []).includes(pid) || (lib.cargos || []).includes(p.cargoId) || (lib.setores || []).map(norm).some(s=>s && [p.setor,p.area,p.areaId].map(norm).includes(s)));
      return atribuida && !registros.some(r=>r.formacaoId===f.id && r.colaboradorId===pid);
    }).map(p=>({f,p}))):[];
    const praticas=registros.flatMap(p=>Object.entries(p.etapas || {}).filter(([,r])=>r.status==='aguardando_validacao').map(([etapaId,r])=>({p,r,etapaId})));
    app.innerHTML=header('escola')+intro('Cuidar de quem aprende.','Organize jornadas, acompanhe dificuldades e valide a prática com evidência.',g.podeGerir?'<a class="botao" href="#/formacao-editor/novo">+ Nova jornada</a>':'')+aviso()+
      '<div class="edu-resumo"><span><strong>'+fs.length+'</strong> jornadas</span><span><strong>'+registros.length+'</strong> formações iniciadas</span>'+(g.podeGerir?'<span><strong>'+aIniciar.length+'</strong> formações a iniciar</span>':'')+'<span><strong>'+praticas.length+'</strong> práticas aguardando retorno</span></div>'+
      '<nav class="edu-atalhos"><a href="#/escola" data-scroll="edu-validacoes">Práticas para validar</a><a href="#/escola" data-scroll="edu-acompanhamento">Acompanhamento individual</a><a href="#/pessoas">Equipe e vínculos RH</a><a href="#/mapa">Histórico anterior</a></nav>'+
      (souAdmin()?'<details class="card"><summary>Responsáveis pela prática · instrutores</summary><p>Escolha quem acompanha as práticas e em quais setores. Depois vincule a pessoa às etapas da jornada. Ninguém pode validar a própria prática.</p><form id="edu-instrutores"><div id="edu-instrutores-lista"></div><p id="edu-instrutores-erro" class="aviso amarelo" role="alert" hidden></p><div class="acoes"><button type="button" id="edu-adicionar-instrutor" class="botao mini suave">+ Adicionar responsável</button><button id="edu-salvar-instrutores" type="submit" class="botao mini">Salvar responsáveis</button></div></form></details>':'')+
      '<section><h2>Jornadas da escola</h2><div class="edu-grid">'+fs.map(f=>'<article class="edu-jornada"><h3>'+esc(f.titulo)+'</h3><p>'+esc(f.setor || 'Geral')+' · versão '+esc(f.versao)+'</p><span class="edu-status '+(f.publicada?'em_andamento':'nao_iniciada')+'">'+(f.ativa===false?'Arquivada':f.publicada?'Liberada':'Em preparação')+'</span><p class="dica">'+(f.etapas || []).length+' etapas · '+(f.liberacao?.pessoas || []).length+' atribuições individuais</p><div class="acoes"><a class="botao mini suave" href="'+rota(f.id)+'">Ver jornada</a>'+(g.podeGerir?'<a class="botao mini" href="#/formacao-editor/'+encodeURIComponent(f.id)+'">Editar e atribuir</a>':'')+'</div></article>').join('')+'</div></section>'+
      '<section class="card" id="edu-validacoes"><h2>Práticas aguardando validação</h2>'+ (praticas.length?praticas.map(({p,r,etapaId},i)=>{const f=fs.find(f=>f.id===p.formacaoId),e=f?.etapas.find(e=>e.id===etapaId);return '<article class="edu-linha"><div><h3>'+esc(p.nome || p.colaboradorId)+' · '+esc(e?.titulo || etapaId)+'</h3><p>'+esc(f?.titulo || p.formacaoId)+'</p><p class="edu-evidencia">'+esc(r.evidencia || 'Sem descrição de evidência')+'</p></div><button class="botao mini" data-validar="'+i+'">Analisar prática</button></article>';}).join(''):'<p class="dica">Nenhuma prática aguardando validação no seu escopo.</p>')+'</section>'+
      '<section class="card" id="edu-acompanhamento"><h2>Acompanhar e apoiar</h2><div class="campo"><label for="edu-busca-pessoa">Buscar pessoa ou jornada</label><input type="search" id="edu-busca-pessoa" placeholder="Nome ou jornada"></div><div id="edu-registros"></div>'+(g.podeGerir?'<h3>Quem ainda precisa começar</h3><p class="dica">Pessoas do seu escopo com jornada liberada por pessoa, função ou setor e sem registro de início.</p><div id="edu-iniciar"></div>':'')+'</section></div>';
    fim(app);
    const instrutores=$('#edu-instrutores');if(instrutores){
      let linhas=Object.entries(g.instrutores || {}).map(([usuario,setores])=>({usuario,setores:[...setores]}));
      const setoresAtuais=[...new Set([...setores(),...fs.map(f=>f.setor),...(g.pessoas || []).flatMap(p=>[p.setor,p.area])].filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
      const lerInstrutores=()=>{linhas=$$('[data-instrutor-linha]').map(el=>({usuario:$('[data-instrutor-pessoa]',el).value,setores:Array.from($('[data-instrutor-setores]',el).selectedOptions).map(o=>o.value)}));};
      const pintarInstrutores=()=>{
        $('#edu-instrutores-lista').innerHTML=linhas.map((l,i)=>'<div class="edu-doc-editor" data-instrutor-linha><div class="edu-form-grid"><div class="campo"><label for="edu-instrutor-'+i+'">Responsável '+(i+1)+'</label><select id="edu-instrutor-'+i+'" data-instrutor-pessoa required><option value="">Selecione uma pessoa</option>'+opcoesResponsaveis(g.pessoas || [],[l.usuario].filter(Boolean))+'</select></div><div class="campo"><label for="edu-instrutor-setores-'+i+'">Setores em que pode acompanhar</label><select id="edu-instrutor-setores-'+i+'" data-instrutor-setores multiple size="4" required>'+[...setoresAtuais,...l.setores.filter(s=>!setoresAtuais.includes(s))].map(s=>'<option value="'+esc(s)+'"'+(l.setores.includes(s)?' selected':'')+'>'+esc(s)+(setoresAtuais.includes(s)?'':' · setor anterior (conferir)')+'</option>').join('')+'</select><p class="dica">Você pode selecionar mais de um setor.</p></div></div><button class="botao mini suave" type="button" data-remover-instrutor="'+i+'">Remover responsável</button></div>').join('') || '<p class="dica">Nenhum responsável configurado. Adicione uma pessoa com acesso vinculado ao RH.</p>';
        $$('[data-remover-instrutor]').forEach(bt=>bt.onclick=()=>{lerInstrutores();linhas.splice(Number(bt.dataset.removerInstrutor),1);pintarInstrutores();});
      };
      $('#edu-adicionar-instrutor').onclick=()=>{lerInstrutores();linhas.push({usuario:'',setores:[]});pintarInstrutores();};
      instrutores.onsubmit=async ev=>{ev.preventDefault();lerInstrutores();const mapa={},el=$('#edu-instrutores-erro');el.hidden=true;for(const l of linhas){if(!l.usuario || !l.setores.length){el.textContent='Escolha a pessoa e pelo menos um setor para cada responsável.';el.hidden=false;return;}if(Object.hasOwn(mapa,l.usuario)){el.textContent='Essa pessoa aparece mais de uma vez. Reúna os setores em um único cadastro.';el.hidden=false;return;}mapa[l.usuario]=l.setores;}const bt=$('#edu-salvar-instrutores');bt.disabled=true;const r=await executar({operacao:'configurarInstrutores',instrutores:mapa},async()=>{await carregar();if(snapshot)gestao(app);toast('Responsáveis registrados.');});if(!r)bt.disabled=false;};
      pintarInstrutores();
    }
    function registrosHtml(){const q=norm($('#edu-busca-pessoa').value);$('#edu-registros').innerHTML=registros.filter(p=>norm((p.nome || p.colaboradorId)+' '+(fs.find(f=>f.id===p.formacaoId)?.titulo || '')).includes(q)).map((p)=>{const f=fs.find(f=>f.id===p.formacaoId),novaVersao=!!p.formacaoVersao && p.formacaoVersao!==f?.versao,etapas=(f?.etapas || []).map(e=>({...e,status:novaVersao || e.statusFonte==='pendente'?'revisar':p.etapas?.[e.id]?.status || 'nao_iniciada'})),pr=progresso({...f,etapas,progresso:null},p),pend=etapas.some(e=>e.status==='revisar');return '<article class="edu-linha"><div><h3>'+esc(p.nome || p.colaboradorId)+'</h3><p>'+esc(f?.titulo || p.formacaoId)+' · '+pr.concluidas+'/'+pr.total+' etapas</p>'+selo(pend?'revisar':pr.percentual===100?'concluida':'em_andamento')+'<details><summary>Registros e versões</summary>'+historicoHtml(p)+'</details></div>'+(g.podeGerir?'<button class="botao mini suave" data-reciclar="'+esc(p.colaboradorId)+'" data-formacao="'+esc(p.formacaoId)+'">Programar reciclagem</button>':'')+'</article>';}).join('') || '<p class="dica">Nenhuma formação iniciada neste filtro.</p>';
      const iniciar=$('#edu-iniciar');if(iniciar)iniciar.innerHTML=aIniciar.filter(({f,p})=>norm(p.nome+' '+f.titulo).includes(q)).map(({f,p})=>'<article class="edu-linha"><div><h3>'+esc(p.nome || p.colaboradorId)+'</h3><p>'+esc(f.titulo)+' · '+esc([p.funcao,p.setor || p.area].filter(Boolean).join(' · ') || 'Função a conferir')+'</p>'+selo('nao_iniciada')+(!p.usuario?'<p class="dica">Acesso pessoal ao painel a conferir.</p>':'')+'</div><a class="botao mini suave" href="#/formacao-editor/'+encodeURIComponent(f.id)+'">Conferir atribuição</a></article>').join('') || '<p class="dica">Nenhuma pessoa com início pendente neste filtro.</p>';
      $$('[data-reciclar]').forEach(bt=>bt.onclick=()=>{const dlg=abrirModal('<h3>Programar reciclagem</h3><p>O histórico anterior será preservado. Informe por que esta formação precisa ser refeita.</p><form id="edu-rec-form"><div class="campo"><label for="edu-rec-motivo">Motivo</label><textarea id="edu-rec-motivo" required maxlength="1000"></textarea></div><button class="botao">Confirmar reciclagem</button><button class="botao suave" type="button" id="edu-rec-cancelar">Cancelar</button></form>');$('#edu-rec-cancelar').onclick=()=>dlg.remove();$('#edu-rec-form').onsubmit=async ev=>{ev.preventDefault();const res=await executar({operacao:'reciclar',colaboradorId:bt.dataset.reciclar,formacaoId:bt.dataset.formacao,motivo:$('#edu-rec-motivo').value},async()=>{dlg.remove();await carregar();gestao(app);toast('Reciclagem registrada. Histórico preservado.');});if(!res)toast(erro,'erro');};});
    }
    $('#edu-busca-pessoa').oninput=registrosHtml;registrosHtml();
    $$('[data-validar]').forEach(bt=>bt.onclick=()=>{const {p,r,etapaId}=praticas[Number(bt.dataset.validar)],f=fs.find(f=>f.id===p.formacaoId),e=f?.etapas.find(e=>e.id===etapaId);const dlg=abrirModal('<h3>Validar prática de '+esc(p.nome || p.colaboradorId)+'</h3><p>'+esc(e?.titulo || etapaId)+'</p><p class="edu-evidencia">'+esc(r.evidencia)+'</p><ul>'+(e?.checklist || []).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><form id="edu-validar-form"><div class="campo"><label for="edu-validar-feedback">Retorno sobre o que foi observado</label><textarea id="edu-validar-feedback" required maxlength="2000"></textarea></div><div class="campo"><label for="edu-validar-resultado">Resultado</label><select id="edu-validar-resultado"><option value="revisar">Precisa praticar novamente</option><option value="aprovado">Prática validada</option></select></div><p class="dica">Confirme somente após acompanhar a execução. Pontos e medalhas não substituem esta avaliação.</p><button class="botao">Registrar avaliação</button><button class="botao suave" type="button" id="edu-val-cancelar">Cancelar</button></form>');$('#edu-val-cancelar').onclick=()=>dlg.remove();$('#edu-validar-form').onsubmit=async ev=>{ev.preventDefault();const btn=ev.target.querySelector('button');btn.disabled=true;const res=await executar({operacao:'validar',colaboradorId:p.colaboradorId,formacaoId:p.formacaoId,etapaId,formacaoVersao:f?.versao,aprovado:$('#edu-validar-resultado').value==='aprovado',feedback:$('#edu-validar-feedback').value},async()=>{dlg.remove();await carregar();gestao(app);toast('Avaliação confirmada pelo servidor.');});if(!res)btn.disabled=false;};});
  }
  function opcoesResponsaveis(pessoas,selecionados){
    const conhecidos=new Map(pessoas.filter(p=>p.usuario).map(p=>[norm(p.usuario),p]));
    const valores=[...conhecidos.keys(),...selecionados.filter(u=>!conhecidos.has(u))];
    return [...new Set(valores)].sort((a,b)=>(conhecidos.get(a)?.nome || a).localeCompare(conhecidos.get(b)?.nome || b,'pt-BR')).map(u=>{const p=conhecidos.get(u);return '<option value="'+esc(u)+'"'+(selecionados.includes(u)?' selected':'')+'>'+esc(p?(p.nome || u)+' · '+u:u+' · vínculo anterior (conferir RH)')+'</option>';}).join('');
  }
  function novaEtapa(tipo){return {id:uuid(),titulo:tipos[tipo],tipo,obrigatoria:true,preparacaoPendente:true,prerequisitos:[],pontos:10,conteudo:{aprender:'',importancia:'',comoFazer:'',erros:'',evidencia:''},fontes:[],documentos:[],quiz:[],minimoAcerto:70,maxTentativas:3,validadores:[],checklist:[]};}
  function editor(app){
    if(!snapshot.gestao?.podeGerir){location.hash='#/';return;}
    const anterior=(snapshot.formacoes || []).find(f=>f.id===ROTA.arg),novo=ROTA.arg==='novo';
    if(!novo && !anterior){location.hash='#/escola';return;}
    const f=JSON.parse(JSON.stringify(anterior || {id:uuid(),titulo:'',versao:'1.0',setor:'',ativa:true,publicada:false,liberacao:{pessoas:[],cargos:[],setores:[],todos:false},etapas:Object.keys(tipos).map(novaEtapa)}));
    if(novo)f.etapas.forEach((e,i)=>{if(i)e.prerequisitos=[f.etapas[i-1].id];});
    const pessoas=snapshot.gestao.pessoas || [];
    app.innerHTML=header('escola')+intro(novo?'Uma jornada para formar bem.':f.titulo,'Conteúdo oficial, critério claro e prática acompanhada.','<a class="botao suave mini" href="#/escola">← Gestão da escola</a>')+aviso()+
      '<form id="edu-editor"><section class="card"><h2>Identidade da jornada</h2><div class="edu-form-grid"><div class="campo"><label for="edu-titulo">Nome da jornada</label><input id="edu-titulo" required maxlength="200" value="'+esc(f.titulo)+'"></div><div class="campo"><label for="edu-setor">Setor responsável</label><input id="edu-setor" required list="edu-setores" value="'+esc(f.setor)+'"><datalist id="edu-setores">'+setores().map(s=>'<option value="'+esc(s)+'">').join('')+'</datalist></div><div class="campo"><label for="edu-versao">Versão</label><input id="edu-versao" required maxlength="40" value="'+esc(f.versao)+'"></div></div><p class="dica">Ao alterar o que será ensinado ou avaliado, use uma nova versão. As conclusões anteriores permanecem no histórico.</p><label class="edu-check"><input id="edu-publicada" type="checkbox"'+(f.publicada?' checked':'')+'> Liberar esta jornada para o público selecionado</label><label class="edu-check"><input id="edu-ativa" type="checkbox"'+(f.ativa!==false?' checked':'')+'> Jornada ativa</label></section>'+
      '<section class="card"><h2>Quem pode aprender nesta jornada?</h2><p>Atribua por pessoa, função ou setor. Essa escolha não modifica o cargo no RH.</p>'+(!souAdmin()?'<p class="dica">As funções serão liberadas somente nos setores sob sua gestão.</p>':f.liberacao?.cargosGestor?'<p class="dica">A liberação por função mantém o limite de setores definido na atribuição anterior.</p>':'')+'<div class="edu-form-grid"><div class="campo"><label for="edu-pessoas">Pessoas (vínculo RH)</label><select id="edu-pessoas" multiple size="5">'+pessoas.map(p=>'<option value="'+esc(p.colaboradorId || p.id.replace(/^p-/,''))+'"'+((f.liberacao?.pessoas || []).includes(p.colaboradorId || p.id.replace(/^p-/,''))?' selected':'')+'>'+esc(p.nome)+(p.funcao?' · '+esc(p.funcao):'')+'</option>').join('')+'</select></div><div class="campo"><label for="edu-cargos">Funções do RH</label><select id="edu-cargos" multiple size="5">'+[...new Map(pessoas.filter(p=>p.cargoId).map(p=>[p.cargoId,p.funcao || p.cargoId])).entries(),...(f.liberacao?.cargos || []).filter(id=>!pessoas.some(p=>p.cargoId===id)).map(id=>[id,'Função anteriormente atribuída'])].map(([id,nome])=>'<option value="'+esc(id)+'"'+((f.liberacao?.cargos || []).includes(id)?' selected':'')+'>'+esc(nome)+'</option>').join('')+'</select></div><div class="campo"><label for="edu-liberar-setores">Setores liberados</label><select id="edu-liberar-setores" multiple size="5">'+[...new Set([...setores(),...(f.liberacao?.setores || [])])].map(nome=>'<option value="'+esc(nome)+'"'+((f.liberacao?.setores || []).includes(nome)?' selected':'')+'>'+esc(nome)+'</option>').join('')+'</select></div></div><label class="edu-check"><input id="edu-todos" type="checkbox"'+(f.liberacao?.todos?' checked':'')+'> Liberar para todas as pessoas com vínculo RH válido</label></section>'+
      '<section class="card"><div class="secao-titulo"><h2>Etapas da formação</h2><button type="button" class="botao mini suave" id="edu-add-etapa">+ Etapa</button></div><p class="dica">As sete etapas iniciais são uma estrutura de preparação. Inclua os conteúdos oficiais e critérios reais antes de liberar.</p><div id="edu-etapas-editor"></div></section><div id="edu-editor-erro" role="alert" class="aviso amarelo" hidden></div><div class="edu-salvar"><button class="botao" type="submit">Salvar jornada</button><span>Confirmação após gravação no servidor.</span></div></form></div>';
    function ler(){
      $$('[data-ee]').forEach(el=>{const e=f.etapas.find(e=>e.id===el.dataset.ee);if(!e)return;
        $$('[data-campo]',el).forEach(input=>{const k=input.dataset.campo;if(k.startsWith('conteudo.'))e.conteudo[k.split('.')[1]]=input.value.trim();else if(input.type==='checkbox')e[k]=input.checked;else if(input.type==='number'){if(input.value)e[k]=Number(input.value);else delete e[k];}else e[k]=input.value.trim();});
        e.prerequisitos=Array.from($('[data-pre]',el).selectedOptions).map(o=>o.value);
        e.validadores=Array.from($('[data-validadores]',el).selectedOptions).map(o=>o.value);
        e.checklist=$('[data-checklist]',el).value.split('\n').map(x=>x.trim()).filter(Boolean);
        e.fontes=Array.from($('[data-fontes]',el).selectedOptions).map(o=>{const [tipo,refId]=o.value.split('|'),r=STORE.um(tipo==='pop'?'pops':'treinamentos',refId);const previa=(e.fontes || []).find(x=>x.tipo===tipo&&x.refId===refId);return {tipo,refId,versao:previa?.versao || r?.versao || '1.0',oficialConfirmado:previa?.oficialConfirmado || $('[data-fontes-oficiais]',el).checked};});
        e.documentos=$$('[data-doc]',el).map(d=>({titulo:$('[data-doc-titulo]',d).value.trim(),url:$('[data-doc-url]',d).value.trim(),versao:$('[data-doc-versao]',d).value.trim(),oficialConfirmado:$('[data-doc-oficial]',d).checked}));
        e.quiz=$$('[data-q]',el).map(q=>({id:q.dataset.q,pergunta:$('[data-pergunta]',q).value.trim(),opcoes:$('[data-opcoes]',q).value.split('\n').map(x=>x.trim()).filter(Boolean),correta:Number($('[data-correta]',q).value)-1,explicacao:$('[data-explicacao]',q).value.trim(),revisar:$('[data-revisar]',q).value.trim()}));
      });
    }
    function pintar(){
      const conteudos=STORE.col('pops').map(p=>({...p,tipo:'pop'})).concat(STORE.col('treinamentos').map(p=>({...p,tipo:'treinamento'})));
      $('#edu-etapas-editor').innerHTML=f.etapas.map((e,i)=>'<details class="edu-editar-etapa" data-ee="'+esc(e.id)+'"'+(i===0?' open':'')+'><summary><span class="edu-numero">'+(i+1)+'</span> '+esc(e.titulo)+'</summary><div class="edu-form-grid"><div class="campo"><label>Título</label><input data-campo="titulo" required maxlength="200" value="'+esc(e.titulo)+'"></div><div class="campo"><label>Tipo</label><select data-campo="tipo">'+Object.entries(tipos).map(([k,v])=>'<option value="'+k+'"'+(e.tipo===k?' selected':'')+'>'+v+'</option>').join('')+'</select></div><div class="campo"><label>Pontos por conclusão</label><input type="number" min="0" max="1000" step="1" data-campo="pontos" value="'+Number(e.pontos || 0)+'"></div><div class="campo"><label>Duração estimada (minutos, opcional)</label><input data-campo="duracaoMinutos" type="number" min="1" max="10000" value="'+esc(e.duracaoMinutos || '')+'"></div></div><label class="edu-check"><input data-campo="obrigatoria" type="checkbox"'+(e.obrigatoria!==false?' checked':'')+'> Etapa obrigatória</label><label class="edu-check"><input data-campo="preparacaoPendente" type="checkbox"'+(e.preparacaoPendente?' checked':'')+'> Conteúdo em preparação (etapa fica bloqueada)</label><div class="campo"><label>Pré-requisitos</label><select data-pre multiple size="3">'+f.etapas.filter(x=>x.id!==e.id).map(x=>'<option value="'+esc(x.id)+'"'+((e.prerequisitos || []).includes(x.id)?' selected':'')+'>'+esc(x.titulo)+'</option>').join('')+'</select></div>'+
        '<div class="edu-form-grid">'+[['aprender','O que a pessoa aprenderá?'],['importancia','Por que isso importa?'],['comoFazer','Como fazer corretamente?'],['erros','Quais erros evitar?'],['evidencia','Como demonstrará que aprendeu?']].map(([k,l])=>'<div class="campo"><label>'+l+'</label><textarea data-campo="conteudo.'+k+'" maxlength="8000">'+esc(e.conteudo?.[k] || '')+'</textarea></div>').join('')+'</div>'+
        '<div class="campo"><label>POPs e treinamentos oficiais utilizados</label><select data-fontes multiple size="4">'+conteudos.map(x=>'<option value="'+esc(x.tipo+'|'+x.id)+'"'+((e.fontes || []).some(r=>r.tipo===x.tipo&&r.refId===x.id)?' selected':'')+'>'+esc(x.codigo || x.titulo)+' · v'+esc(x.versao || '1.0')+'</option>').join('')+'</select><p class="dica">Cada vínculo guarda a versão estudada. Se a fonte mudar, confira a etapa e atualize a referência.</p><label class="edu-check"><input type="checkbox" data-fontes-oficiais> Conferi as versões oficiais dos treinamentos selecionados</label><button type="button" class="botao mini suave" data-atualizar-fontes="'+i+'">Usar versões atuais das fontes selecionadas</button></div><h3>Documentos, imagens ou vídeos oficiais</h3><p class="dica">Use links HTTPS com controle de acesso adequado. Os documentos internos não devem ser publicados em uma pasta pública.</p>'+(e.documentos || []).map((d,n)=>'<div class="edu-doc-editor" data-doc><div class="campo"><label>Título do material</label><input data-doc-titulo value="'+esc(d.titulo)+'"></div><div class="campo"><label>Link HTTPS</label><input data-doc-url type="url" value="'+esc(d.url)+'"></div><div class="campo"><label>Versão</label><input data-doc-versao value="'+esc(d.versao)+'"></div><label class="edu-check"><input type="checkbox" data-doc-oficial'+(d.oficialConfirmado?' checked':'')+'> Conferi que esta é a versão oficial autorizada</label><button class="botao mini suave" type="button" data-rem-doc="'+i+':'+n+'">Remover material</button></div>').join('')+'<button class="botao mini suave" type="button" data-add-doc="'+i+'">+ Material</button>'+
        '<h3>Avaliação de compreensão</h3><div class="edu-form-grid"><div class="campo"><label>Acerto mínimo (%)</label><input data-campo="minimoAcerto" type="number" min="1" max="100" value="'+(e.minimoAcerto ?? 70)+'"></div><div class="campo"><label>Máximo de tentativas</label><input data-campo="maxTentativas" type="number" min="1" max="20" value="'+(e.maxTentativas || 3)+'"></div></div>'+(e.quiz || []).map((q,n)=>'<div class="edu-questao-editor" data-q="'+esc(q.id)+'"><h4>Questão '+(n+1)+'</h4><div class="campo"><label>Situação ou pergunta</label><textarea data-pergunta>'+esc(q.pergunta)+'</textarea></div><div class="edu-form-grid"><div class="campo"><label>Alternativas (uma por linha)</label><textarea data-opcoes>'+esc(q.opcoes.join('\n'))+'</textarea></div><div class="campo"><label>Número da alternativa correta</label><input type="number" min="1" max="10" data-correta value="'+(q.correta+1)+'"></div></div><div class="campo"><label>Explicação após responder</label><textarea data-explicacao>'+esc(q.explicacao)+'</textarea></div><div class="campo"><label>O que rever se precisar de apoio?</label><input data-revisar value="'+esc(q.revisar || '')+'"></div><button type="button" class="botao mini suave" data-rem-q="'+i+':'+n+'">Remover questão</button></div>').join('')+'<button class="botao mini suave" type="button" data-add-q="'+i+'">+ Questão prática</button>'+
        '<h3>Prática e acompanhamento</h3><div class="edu-form-grid"><div class="campo"><label>Checklist da prática (um item por linha)</label><textarea data-checklist>'+esc((e.checklist || []).join('\n'))+'</textarea></div><div class="campo"><label>Quem valida esta prática?</label><select data-validadores multiple size="4">'+opcoesResponsaveis(pessoas,e.validadores || [])+'</select><p class="dica">Selecione uma ou mais pessoas. Elas também precisam estar autorizadas para o setor em Responsáveis pela prática. Esse vínculo não concede acesso administrativo.</p></div></div><div class="acoes"><button type="button" class="botao mini suave" data-mover="'+i+':-1"'+(!i?' disabled':'')+'>↑ Subir</button><button type="button" class="botao mini suave" data-mover="'+i+':1"'+(i===f.etapas.length-1?' disabled':'')+'>↓ Descer</button><button type="button" class="botao mini fantasma" data-rem-etapa="'+i+'">Remover etapa</button></div></details>').join('');
      $$('[data-add-doc]').forEach(bt=>bt.onclick=()=>{ler();f.etapas[+bt.dataset.addDoc].documentos.push({titulo:'',url:'',versao:'1.0'});pintar();});
      $$('[data-add-q]').forEach(bt=>bt.onclick=()=>{ler();f.etapas[+bt.dataset.addQ].quiz.push({id:uuid(),pergunta:'',opcoes:['',''],correta:0,explicacao:'',revisar:''});pintar();});
      for(const [seletor,prop] of [['remDoc','documentos'],['remQ','quiz']])$$('[data-'+(seletor==='remDoc'?'rem-doc':'rem-q')+']').forEach(bt=>bt.onclick=()=>{ler();const[i,n]=bt.dataset[seletor].split(':').map(Number);f.etapas[i][prop].splice(n,1);pintar();});
      $$('[data-mover]').forEach(bt=>bt.onclick=()=>{ler();const[i,d]=bt.dataset.mover.split(':').map(Number);[f.etapas[i],f.etapas[i+d]]=[f.etapas[i+d],f.etapas[i]];pintar();});
      $$('[data-rem-etapa]').forEach(bt=>bt.onclick=()=>{if(!confirm('Remover esta etapa da nova estrutura? O histórico confirmado permanecerá registrado.'))return;ler();const i=+bt.dataset.remEtapa,id=f.etapas[i].id;f.etapas.splice(i,1);for(const e of f.etapas)e.prerequisitos=e.prerequisitos.filter(k=>k!==id);pintar();});
      $$('[data-atualizar-fontes]').forEach(bt=>bt.onclick=()=>{ler();const e=f.etapas[+bt.dataset.atualizarFontes];e.fontes=e.fontes.map(r=>({...r,versao:STORE.um(r.tipo==='pop'?'pops':'treinamentos',r.refId)?.versao || r.versao,oficialConfirmado:false}));toast('Referências atualizadas no formulário. Revise o conteúdo e a versão da jornada antes de salvar.');});
      associarRotulos($('#edu-editor'));
    }
    $('#edu-add-etapa').onclick=()=>{ler();f.etapas.push(novaEtapa('continua'));pintar();};
    $('#edu-editor').onsubmit=async ev=>{ev.preventDefault();ler();Object.assign(f,{titulo:$('#edu-titulo').value.trim(),versao:$('#edu-versao').value.trim(),setor:$('#edu-setor').value.trim(),ativa:$('#edu-ativa').checked,publicada:$('#edu-publicada').checked,liberacao:{pessoas:Array.from($('#edu-pessoas').selectedOptions).map(o=>o.value),cargos:Array.from($('#edu-cargos').selectedOptions).map(o=>o.value),setores:Array.from($('#edu-liberar-setores').selectedOptions).map(o=>o.value),todos:$('#edu-todos').checked}});const bt=ev.target.querySelector('button[type=submit]');bt.disabled=true;const res=await executar({operacao:'salvarFormacao',formacao:f,expectedRevision:anterior?._serverRevision ?? anterior?.revision ?? 0},async()=>{toast('Jornada salva no servidor.');location.hash='#/escola';});if(!res){bt.disabled=false;const el=$('#edu-editor-erro');el.hidden=false;el.textContent=erro;el.focus();}};
    pintar();fim(app);
  }
  return {render,zerar,carregar,progresso,bloqueio,status,tipos,estadoEnvio,conferirEstado,podeAcompanhar};
})();
