/* Acompanhamento usa apenas os registros filtrados e autorizados pelo servidor. */
window.ESCOLA_GESTAO=(()=>{
 const A=()=>ACADEMIA,F=(...a)=>A().campo(...a),T=(...a)=>A().area(...a);
 const vigente='https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes';
 const opts=(valores,atual='')=>valores.map(([v,t])=>'<option value="'+esc(v)+'"'+(atual===v?' selected':'')+'>'+esc(t)+'</option>').join('');
 async function render(app){const hash=location.hash;A().layout(app,'Sua escola, organizada','Consultando os registros autorizados…');try{
  if(['alunos','aluno','avaliacoes'].includes(ROTA.nome)){const d=await STORE.api('escola',{operacao:'painel'});if(hash!==location.hash)return;return ROTA.nome==='avaliacoes'?avaliacoes(app,d):alunos(app,d);}
  if(ROTA.nome==='nrs'){const d=await A().api('capacitacoes');if(hash===location.hash)nrs(app,d);return;}
  const d=await A().api('perfis');if(hash!==location.hash)return;
  if(ROTA.nome==='perfil-editor')perfilEditor(app,d);else if(ROTA.nome==='perfil-teste')perfilTeste(app,d);else perfis(app,d);
 }catch(e){A().layout(app,'Precisamos retomar a consulta',e.message||'Tente novamente com conexão.','<button class="botao" id="eg-retentar">Tentar novamente</button>');$('#eg-retentar').onclick=()=>render(app);}}
 function avaliacoes(app,d){const el=A().layout(app,'Minhas avaliações','Veja o que já demonstrou e onde precisa revisar.');const itens=d.formacoes.filter(f=>f.liberadaParaMim).flatMap(f=>f.etapas.filter(e=>e.quiz?.length||e.avaliacaoPendente).map(e=>({f,e,r:d.aprendizagem.find(r=>r.formacaoId===f.id)?.etapas?.[e.id]})));
  el.innerHTML='<div class="edu-grid">'+(itens.map(({f,e,r})=>'<article class="card"><span class="ac-kicker">'+esc(f.titulo)+'</span><h2>'+esc(e.titulo)+'</h2><p>'+ (e.avaliacaoPendente?'Avaliação em revisão pelo responsável.':r?.compreensaoEm?'Aprendizagem avaliada':r?.leituraEm?'Avaliação disponível':'Conclua o estudo para responder')+'</p><p class="dica">'+(r?.tentativas?.length||0)+' tentativas'+(r?.tentativas?.length?' · última nota '+r.tentativas.at(-1).nota+'%':'')+'</p><a class="botao mini" href="#/formacao/'+encodeURIComponent(f.id)+'/'+encodeURIComponent(e.id)+'">'+(r?.compreensaoEm?'Consultar resultado':'Abrir etapa')+'</a></article>').join('')||'<section class="card"><h2>Suas avaliações aparecerão aqui</h2><p>Elas acompanham as jornadas atribuídas e as versões revisadas pela gestão.</p></section>')+'</div>';
 }
 function alunos(app,d){if(!d.gestao?.podeGerir){A().layout(app,'Acompanhamento restrito','Sua conta não possui permissão de gestão dos alunos.');return;}const ps=d.gestao.pessoas,rs=d.gestao.registros,fs=d.formacoes;
  const cursos=p=>fs.filter(f=>(f.pessoasLiberadas||[]).includes(p.colaboradorId)||rs.some(r=>r.colaboradorId===p.colaboradorId&&r.formacaoId===f.id));
  const estado=(p,f)=>{const r=rs.find(r=>r.colaboradorId===p.colaboradorId&&r.formacaoId===f.id);return f.prazo&&f.prazo<new Date().toLocaleDateString('en-CA')&&!r?.concluidaEm?'Prazo vencido':!r?'Não iniciado':r.formacaoVersao!==f.versao?'Revisão necessária':r.concluidaEm?'Concluído':Object.values(r.etapas||{}).some(e=>e.status==='revisar')?'Precisa de apoio':Object.values(r.etapas||{}).some(e=>e.status==='aguardando_validacao')?'Aguardando validação':'Em estudo';};
  if(ROTA.nome==='aluno'){const p=ps.find(p=>p.colaboradorId===ROTA.arg);if(!p){A().layout(app,'Aluno não disponível','Confira seu escopo de acesso.');return;}const el=A().layout(app,p.nome,[p.funcao,p.setor||p.area].filter(Boolean).join(' · '),'<a class="botao mini suave" href="#/alunos">← Alunos</a>');
   el.innerHTML='<p class="dica">Vínculo único do RH · '+esc(p.colaboradorId)+'</p><div class="edu-grid">'+cursos(p).map(f=>{const r=rs.find(r=>r.colaboradorId===p.colaboradorId&&r.formacaoId===f.id);return '<article class="card"><h2>'+esc(f.titulo)+'</h2><span class="edu-status">'+estado(p,f)+'</span><p class="dica">Versão '+esc(r?.formacaoVersao||f.versao)+(f.prazo?' · prazo '+fmtData(f.prazo):'')+'</p><p class="dica">Atribuição: '+esc(f.atribuicao?.por||f.atualizadoPor||'Cadastro anterior')+(f.atribuicao?.em?' · '+fmtDataHora(f.atribuicao.em):'')+'</p>'+f.etapas.map(e=>{const a=r?.etapas?.[e.id];return '<details class="eg-etapa"><summary>'+esc(e.titulo)+' · '+esc(r?.formacaoVersao!==f.versao?'Versão anterior':({concluida:'Concluída',em_andamento:'Em estudo',revisar:'Revisão necessária',aguardando_validacao:'Aguardando validação'})[a?.status]||'Não iniciada')+'</summary><p>Leitura: '+(a?.leituraEm?fmtDataHora(a.leituraEm):'Pendente')+'</p>'+((a?.tentativas||[]).map((t,i)=>'<p>Tentativa '+(i+1)+' · '+t.nota+'% · '+fmtDataHora(t.em)+'<br>'+esc(t.aprovada?'Aprovada':'Revisão necessária')+'</p>').join(''))+(a?.validacao?'<p>Prática: '+esc(a.validacao.feedback)+' · '+esc(a.validacao.por)+'</p>':'')+'</details>';}).join('')+'<a class="botao mini suave" href="#/formacao-editor/'+encodeURIComponent(f.id)+'">Gerenciar atribuição</a></article>';}).join('')+'</div><section class="card"><h2>Histórico complementar</h2><div id="eg-historico-extra">Consultando NRs e resultados autorizados…</div><a class="botao mini suave" href="#/escola">Práticas e apoio à aprendizagem</a></section>';
   Promise.all([A().api('capacitacoes'),A().api('perfis')]).then(([nr,perfil])=>{const box=$('#eg-historico-extra');if(!box)return;box.innerHTML='<h3>Capacitações de NRs</h3>'+nr.registros.filter(r=>r.colaboradorId===p.colaboradorId).map(r=>'<p>'+esc(r.titulo)+' · '+esc(r.status)+(r.vencimento?' · validade '+fmtData(r.vencimento):'')+'</p>').join('')+'<h3>Perfil e Desenvolvimento</h3>'+perfil.resultados.filter(r=>r.colaboradorId===p.colaboradorId).map(resultadoHtml).join('')+'<p class="dica">Resultados de perfil aparecem somente para os responsáveis expressamente autorizados no instrumento.</p>';}).catch(e=>{if($('#eg-historico-extra'))$('#eg-historico-extra').textContent=e.message;});return;
  }
  const el=A().layout(app,'Alunos e desenvolvimento','Identifique quem precisa começar, revisar ou receber acompanhamento.','<a class="botao" href="#/formacao-editor/novo">Atribuir formação</a>');
  el.innerHTML='<section class="card"><div class="edu-form-grid">'+F('aluno-busca','Buscar aluno','','type="search"')+'<div class="campo"><label for="eg-setor">Setor</label><select id="eg-setor"><option value="">Todos</option>'+opts([...new Set(ps.map(p=>p.setor||p.area))].map(s=>[s,s]))+'</select></div><div class="campo"><label for="eg-cargo">Cargo</label><select id="eg-cargo"><option value="">Todos</option>'+opts([...new Set(ps.map(p=>p.funcao))].map(s=>[s,s]))+'</select></div><div class="campo"><label for="eg-curso">Treinamento</label><select id="eg-curso"><option value="">Todos</option>'+opts(fs.map(f=>[f.id,f.titulo]))+'</select></div><div class="campo"><label for="eg-situacao">Situação</label><select id="eg-situacao"><option value="">Todas</option>'+opts(['Não iniciado','Prazo vencido','Em estudo','Concluído','Revisão necessária','Precisa de apoio','Aguardando validação'].map(s=>[s,s]))+'</select></div></div><div id="eg-alunos"></div></section>';
  const pintar=()=>{const q=norm($('#ac-aluno-busca').value),setor=$('#eg-setor').value,cargo=$('#eg-cargo').value,curso=$('#eg-curso').value,sit=$('#eg-situacao').value;const lista=ps.filter(p=>norm(p.nome).includes(q)&&(!setor||setor===(p.setor||p.area))&&(!cargo||cargo===p.funcao)&&(!curso||cursos(p).some(f=>f.id===curso))&&(!sit||cursos(p).some(f=>(!curso||f.id===curso)&&estado(p,f)===sit)));$('#eg-alunos').innerHTML='<p class="dica">'+lista.length+' aluno(s)</p>'+lista.map(p=>'<article class="edu-linha"><div><h2><a href="#/aluno/'+encodeURIComponent(p.colaboradorId)+'">'+esc(p.nome)+'</a></h2><p>'+esc([p.funcao,p.setor||p.area].filter(Boolean).join(' · '))+'</p><p class="dica">'+cursos(p).length+' formações · '+cursos(p).filter(f=>estado(p,f)==='Concluído').length+' concluídas</p></div><a class="botao mini suave" href="#/aluno/'+encodeURIComponent(p.colaboradorId)+'">Acompanhar</a></article>').join('');};for(const s of ['#ac-aluno-busca','#eg-setor','#eg-cargo','#eg-curso','#eg-situacao'])$(s).oninput=pintar;pintar();
 }
 function nrs(app,d){const el=A().layout(app,'Normas Regulamentadoras — NRs','Consulta, formação teórica e validação da capacitação são registros distintos.',d.podeGerir?'<a class="botao" href="#/material-editor/novo-nr">Cadastrar NR</a>':'');const hoje=new Date().toISOString().slice(0,10);
  el.innerHTML='<section class="card ac-nr-intro"><h2>Segurança se aprende com responsabilidade.</h2><p>O responsável define público, requisitos, evidências e reciclagem com base na norma vigente. Um questionário não substitui prática, avaliação presencial ou requisitos profissionais.</p><a href="'+vigente+'" target="_blank" rel="noopener noreferrer">Consultar normas vigentes no Ministério do Trabalho e Emprego ↗</a></section><div class="edu-resumo"><span><strong>'+d.normas.length+'</strong> normas cadastradas</span><span><strong>'+(d.pendencias||[]).filter(r=>r.situacao!=='Reciclagem vencida').length+'</strong> capacitações pendentes</span><span><strong>'+d.registros.filter(r=>r.vencimento&&r.vencimento<hoje).length+'</strong> reciclagens vencidas</span></div><div class="edu-grid">'+(d.normas.map(m=>'<article class="card"><span class="ac-kicker">NR '+esc(m.nr?.numero||'')+'</span><h2>'+esc(m.titulo)+'</h2><p>'+esc(m.nr?.publico||m.objetivo)+'</p><p class="dica">Versão consultada: '+esc(m.nr?.versaoOficial||m.versao)+'</p><a class="botao mini" href="#/material/'+encodeURIComponent(m.id)+'">Estudar norma integral</a>'+(m.podeRegistrar?'<button class="botao mini suave" data-nr="'+esc(m.id)+'">Registrar capacitação</button>':'')+(d.podeGerir?'<a class="botao mini fantasma" href="#/material-editor/'+encodeURIComponent(m.id)+'">Configurar e atribuir</a>':'')+'</article>').join('')||'<section class="card"><h2>Biblioteca em preparação</h2><p>A gestão precisa selecionar as normas aplicáveis e conferir a versão e os requisitos com o responsável.</p></section>')+'</div><section class="card"><h2>Quem precisa avançar</h2>'+((d.pendencias||[]).map(p=>'<article class="edu-linha"><div><b>'+esc(p.nome)+'</b><p>'+esc(p.titulo)+'</p></div><span class="edu-status aguardando_validacao">'+esc(p.situacao)+'</span></article>').join('')||'<p>Nenhuma pendência nas atribuições deste escopo.</p>')+'</section><section class="card"><h2>Realizações, pendências e reciclagens</h2>'+ (d.registros.map(r=>'<details class="eg-etapa"><summary>'+esc(r.nome)+' · '+esc(r.titulo)+' · '+(r.vencimento&&r.vencimento<hoje?'Reciclagem vencida':r.status==='concluida'?'Capacitação registrada':'Etapas pendentes')+'</summary>'+r.etapas.map(e=>'<p>'+(e.cumprida?'✓ ':'○ ')+esc(e.titulo)+': '+esc(e.evidencia||'Pendente')+'</p>').join('')+'<p>Responsável: '+esc(r.validadoPor||'Validação pendente')+(r.vencimento?' · validade '+fmtData(r.vencimento):' · validade não configurada')+'</p>'+ (r.documentos||[]).map(doc=>'<p><a target="_blank" rel="noopener noreferrer" href="'+esc(doc.url)+'">'+esc(doc.titulo)+'</a></p>').join('')+'<p class="dica">'+(r.historico||[]).length+' ciclo(s) anterior(es) preservado(s).</p></details>').join('')||'<p>Nenhuma capacitação registrada neste escopo.</p>')+'</section>';
  $$('[data-nr]').forEach(bt=>bt.onclick=()=>nrRegistro(app,d,d.normas.find(m=>m.id===bt.dataset.nr)));
 }
 function nrRegistro(app,d,m){const dlg=abrirModal('<h2>Registrar capacitação · NR '+esc(m.nr.numero)+'</h2><form id="eg-nr-form"><div class="campo"><label for="eg-nr-aluno">Aluno</label><select id="eg-nr-aluno" required><option value="">Escolha</option>'+opts(d.pessoas.map(p=>[p.colaboradorId,p.nome]))+'</select></div><div id="eg-nr-etapas"></div><button class="botao" type="submit">Salvar registro</button><button class="botao suave" type="button" id="eg-nr-fechar">Cancelar</button></form>');let anterior=null;
  $('#eg-nr-fechar').onclick=()=>dlg.remove();$('#eg-nr-aluno').onchange=()=>{anterior=d.registros.find(r=>r.materialId===m.id&&r.colaboradorId===$('#eg-nr-aluno').value);$('#eg-nr-etapas').innerHTML='<p class="dica">Responsável pela conclusão: '+esc(m.nr.responsavel)+'</p>'+m.nr.requisitos.map((t,i)=>'<div class="eg-etapa"><label class="edu-check"><input type="checkbox" data-nr-ok="'+i+'"'+(anterior?.etapas?.[i]?.cumprida&&anterior.status!=='concluida'?' checked':'')+'> '+esc(t)+'</label>'+T('nr-evidencia-'+i,'Evidência de '+t,anterior?.status!=='concluida'?anterior?.etapas?.[i]?.evidencia||'':'','maxlength="4000"')+'</div>').join('')+F('nr-data','Data da conclusão','','type="date"')+T('nr-documentos','Comprovantes e certificados: título | link HTTPS, um por linha',(anterior?.documentos||[]).map(d=>d.titulo+' | '+d.url).join('\n'))+(anterior?.status==='concluida'?T('nr-motivo','Motivo da reciclagem','','required'):'')+'<label class="edu-check"><input type="checkbox" id="eg-nr-concluir"> Validar a capacitação completa (somente o responsável configurado)</label>';};
  $('#eg-nr-form').onsubmit=async ev=>{ev.preventDefault();if(!$('#eg-nr-aluno').value)return;const bt=ev.target.querySelector('button[type=submit]');bt.disabled=true;const docs=$('#ac-nr-documentos').value.split('\n').filter(x=>x.trim()).map(x=>{const [titulo,...url]=x.split('|');return {titulo:titulo.trim(),url:url.join('|').trim()};});const r=await A().salvar('salvarCapacitacao',{materialId:m.id,colaboradorId:$('#eg-nr-aluno').value,expectedRevision:anterior?._serverRevision||0,etapas:m.nr.requisitos.map((t,i)=>({titulo:t,cumprida:$('[data-nr-ok="'+i+'"]').checked,evidencia:$('#ac-nr-evidencia-'+i).value.trim()})),dataRealizacao:$('#ac-nr-data').value,concluir:$('#eg-nr-concluir').checked,documentos:docs,novoCiclo:anterior?.status==='concluida',motivo:$('#ac-nr-motivo')?.value},async()=>{dlg.remove();await render(app);});if(!r)bt.disabled=false;};
 }
 function resultadoHtml(r){return '<article class="card eg-resultado"><span class="ac-kicker">Autoconhecimento · sem aprovação ou reprovação</span><h2>Seu resultado</h2><h3>'+esc(r.titulo)+'</h3><p>'+esc(r.nome)+'</p><p class="dica">'+fmtDataHora(r.em)+' · versão '+esc(r.versao)+'</p>'+r.resultado.map(x=>'<section><h3>'+esc(x.titulo)+' · '+x.percentual+'%</h3><progress max="100" value="'+x.percentual+'" aria-label="Frequência autorrelatada de '+esc(x.titulo)+'"></progress><p>'+esc(x.orientacao)+'</p><ul>'+x.recomendacoes.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul></section>').join('')+'<details><summary>Como o resultado foi calculado</summary><p>'+esc(r.instrumento.metodologia)+'</p><p>Média das respostas por dimensão, convertida de 0 a 100. Itens inversos têm a ordem invertida. A partir de 67%, é apresentada a orientação de frequência mais alta; abaixo disso, a orientação de desenvolvimento.</p></details><p class="dica">Autorrelato para desenvolvimento. Não é diagnóstico psicológico nem decisão automática sobre o colaborador.</p></article>';}
 function perfis(app,d){const el=A().layout(app,'Perfil e Desenvolvimento','Conheça seus hábitos, reflita sobre sua prática e escolha seu próximo passo.',d.podeGerir?'<a class="botao" href="#/perfil-editor/novo">Novo instrumento</a>':'');el.innerHTML='<div class="edu-grid">'+(d.instrumentos.map(i=>'<article class="card"><span class="ac-kicker">'+(i.aprovacao?'Revisado':'Aguardando revisão')+'</span><h2>'+esc(i.titulo)+'</h2><p>'+esc(i.objetivo)+'</p><p class="dica">'+i.questoes.length+' perguntas'+(i.duracaoMinutos?' · '+i.duracaoMinutos+' min':'')+' · versão '+esc(i.versao)+'</p>'+(i.aprovacao&&i.liberadaParaMim?'<a class="botao mini" href="#/perfil-teste/'+encodeURIComponent(i.id)+'">Responder instrumento</a>':'')+(d.podeGerir?'<a class="botao mini suave" href="#/perfil-editor/'+encodeURIComponent(i.id)+'">Editar e atribuir</a>'+(!i.aprovacao?'<button class="botao mini" data-aprovar-perfil="'+esc(i.id)+'">Revisar e aprovar</button>':''):'')+'</article>').join('')||'<section class="card"><h2>Seu desenvolvimento tem espaço aqui</h2><p>Os instrumentos liberados e revisados pela empresa aparecerão nesta área.</p></section>')+'</div><section><h2>Histórico de aplicações autorizado</h2>'+d.resultados.map(resultadoHtml).join('')+'</section>';
  $$('[data-aprovar-perfil]').forEach(bt=>bt.onclick=()=>{const i=d.instrumentos.find(i=>i.id===bt.dataset.aprovarPerfil);const dlg=abrirModal('<h2>Revisão do instrumento</h2><p>'+esc(i.metodologia)+'</p><p>Autorização: '+esc(i.autorizacao)+'</p><ol>'+i.questoes.map(q=>'<li>'+esc(q.texto)+'</li>').join('')+'</ol><form id="eg-aprovar">'+T('parecer','Parecer da revisão','','required maxlength="4000"')+'<button class="botao">Confirmar aprovação</button><button type="button" class="botao suave" id="eg-cancelar">Cancelar</button></form>');$('#eg-cancelar').onclick=()=>dlg.remove();$('#eg-aprovar').onsubmit=async ev=>{ev.preventDefault();const bt=ev.target.querySelector('button');bt.disabled=true;const r=await A().salvar('aprovarInstrumento',{instrumentoId:i.id,expectedRevision:i._serverRevision,parecer:$('#ac-parecer').value},async()=>{dlg.remove();await render(app);});if(!r)bt.disabled=false;};});
 }
 function perfilTeste(app,d){const i=d.instrumentos.find(x=>x.id===ROTA.arg);if(!i){A().layout(app,'Instrumento não disponível','Confira as atividades liberadas para sua conta.');return;}const rs=d.resultados.filter(r=>r.instrumentoId===i.id&&r.colaboradorId===d.pessoa?.colaboradorId);const el=A().layout(app,i.titulo,i.objetivo,'<a class="botao mini suave" href="#/perfil">← Desenvolvimento</a>');
  if(rs.length){el.innerHTML=rs.map(resultadoHtml).join('')+'<button id="eg-nova-aplicacao" class="botao suave">Realizar nova aplicação</button>';$('#eg-nova-aplicacao').onclick=form;return;}form();
  function form(){el.innerHTML='<section class="card"><h2>Antes de começar</h2><p>'+esc(i.instrucoes)+'</p><p><b>Quem pode consultar:</b> você'+(i.consultores?.length?' e '+esc(i.consultores.join(', ')):'. Nenhum outro responsável foi liberado.')+'</p><details><summary>Metodologia, cálculo e finalidade</summary><p>'+esc(i.metodologia)+'</p><p>As respostas compõem uma média normalizada por dimensão, de 0 a 100. Itens inversos invertem a pontuação. O resultado orienta reflexão, não é diagnóstico e não aprova nem reprova.</p></details></section><form class="card" id="eg-perfil-form">'+i.questoes.map((q,n)=>'<fieldset><legend>'+(n+1)+'. '+esc(q.texto)+'</legend>'+i.escala.map((t,v)=>'<label class="edu-check"><input required type="radio" name="'+esc(q.id)+'" value="'+v+'"> '+esc(t)+'</label>').join('')+'</fieldset>').join('')+'<p id="eg-respondidas" class="dica" aria-live="polite"></p><label class="edu-check"><input type="checkbox" id="eg-ciente" required> Compreendi a finalidade e quem pode consultar meu resultado.</label><button class="botao">Ver meu resultado</button></form>';const form=$('#eg-perfil-form');form.onchange=()=>{$('#eg-respondidas').textContent=form.querySelectorAll('input[type=radio]:checked').length+' de '+i.questoes.length+' respondidas';};form.onchange();form.onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(form),respostas=Object.fromEntries(i.questoes.map(q=>[q.id,fd.has(q.id)?Number(fd.get(q.id)):null]));const bt=form.querySelector('button');bt.disabled=true;const r=await A().salvar('responderPerfil',{instrumentoId:i.id,versao:i.versao,respostas,ciente:$('#eg-ciente').checked},r=>{el.innerHTML=resultadoHtml(r.registro)+'<a class="botao suave" href="#/perfil">Meu histórico</a>';});if(!r)bt.disabled=false;};}
 }
 function perfilEditor(app,d){if(!d.podeGerir){A().layout(app,'Área restrita','A administração prepara os instrumentos.');return;}const antigo=d.instrumentos.find(i=>i.id===ROTA.arg),i=structuredClone(antigo||{id:uuid(),titulo:'',versao:'1.0',setor:'',objetivo:'',instrucoes:'',metodologia:'',autorizacao:'',ativa:true,publicada:false,escala:['Nunca','Às vezes','Sempre'],liberacao:{},visibilidade:[],dimensoes:[{id:uuid(),titulo:'',forte:'',desenvolver:'',recomendacoes:[]}],questoes:[]});if(!i.questoes.length)i.questoes.push({id:uuid(),texto:'',dimensao:i.dimensoes[0].id,inversa:false});
  const el=A().layout(app,antigo?'Editar instrumento':'Preparar um instrumento','O questionário será um rascunho até a revisão e aprovação.','<a class="botao mini suave" href="#/perfil">Voltar</a>');
  el.innerHTML='<form id="eg-instrumento"><section class="card"><div class="edu-form-grid">'+F('inst-titulo','Título',i.titulo,'required maxlength="200"')+F('inst-versao','Versão',i.versao,'required')+F('inst-setor','Setor responsável',i.setor,'required')+F('inst-duracao','Tempo estimado (minutos, opcional)',i.duracaoMinutos||'','type="number" min="1" max="10000"')+'</div>'+T('inst-objetivo','Objetivo',i.objetivo,'required')+T('inst-instrucoes','Instruções',i.instrucoes,'required')+T('inst-metodo','Metodologia e limites',i.metodologia,'required')+T('inst-autorizacao','Autorização de uso',i.autorizacao,'required')+T('inst-escala','Alternativas ordenadas, da menor para a maior frequência',i.escala.join('\n'),'required')+'<p class="dica">Cálculo disponível: média normalizada por dimensão, com itens inversos. Orientação de frequência alta a partir de 67%; abaixo disso, orientação de desenvolvimento. Descreva esse critério na metodologia. Não use instrumentos proprietários sem licença.</p></section><section class="card"><h2>Dimensões de desenvolvimento</h2><div id="eg-dimensoes"></div><button type="button" class="botao mini suave" id="eg-add-dim">Adicionar dimensão</button></section><section class="card"><h2>Perguntas</h2><div id="eg-perguntas"></div><button type="button" class="botao mini suave" id="eg-add-pergunta">Adicionar pergunta</button></section><section class="card"><h2>Público e privacidade</h2>'+A().audienciaHtml(d.pessoas,i.liberacao)+'<div class="campo"><label for="eg-consultores">Quem pode consultar resultados</label><select id="eg-consultores" multiple size="4">'+d.pessoas.map(p=>'<option value="'+esc(p.colaboradorId)+'"'+(i.visibilidade.includes(p.colaboradorId)?' selected':'')+'>'+esc(p.nome)+'</option>').join('')+'</select></div><label class="edu-check"><input type="checkbox" id="eg-inst-publicada"'+(i.publicada?' checked':'')+'> Liberar para o público selecionado</label><label class="edu-check"><input type="checkbox" id="eg-inst-ativa"'+(i.ativa?' checked':'')+'> Instrumento ativo</label></section><button class="botao" type="submit">Salvar instrumento</button></form>';
  const ler=()=>{i.dimensoes.forEach((x,n)=>{x.titulo=$('#ac-dim-titulo-'+n).value.trim();x.forte=$('#ac-dim-forte-'+n).value.trim();x.desenvolver=$('#ac-dim-desenvolver-'+n).value.trim();x.recomendacoes=$('#ac-dim-recs-'+n).value.split('\n').map(x=>x.trim()).filter(Boolean);});i.questoes.forEach((x,n)=>{x.texto=$('#ac-pergunta-'+n).value.trim();x.dimensao=$('#eg-pergunta-dim-'+n).value;x.inversa=$('#eg-pergunta-inversa-'+n).checked;});};
  const pintar=()=>{$('#eg-dimensoes').innerHTML=i.dimensoes.map((x,n)=>'<div class="eg-etapa">'+F('dim-titulo-'+n,'Nome da dimensão '+(n+1),x.titulo,'required')+T('dim-forte-'+n,'Orientação para frequência mais alta '+(n+1),x.forte,'required')+T('dim-desenvolver-'+n,'Orientação para desenvolver '+(n+1),x.desenvolver,'required')+T('dim-recs-'+n,'Conteúdos e ações recomendados '+(n+1),x.recomendacoes.join('\n'))+'</div>').join('');$('#eg-perguntas').innerHTML=i.questoes.map((q,n)=>'<div class="eg-etapa">'+T('pergunta-'+n,'Pergunta '+(n+1),q.texto,'required')+'<div class="campo"><label for="eg-pergunta-dim-'+n+'">Dimensão da pergunta '+(n+1)+'</label><select id="eg-pergunta-dim-'+n+'">'+opts(i.dimensoes.map((d,n)=>[d.id,d.titulo||'Dimensão '+(n+1)]),q.dimensao)+'</select></div><label class="edu-check"><input type="checkbox" id="eg-pergunta-inversa-'+n+'"'+(q.inversa?' checked':'')+'> Item de pontuação inversa</label><button type="button" class="botao mini fantasma" data-rem-pergunta="'+n+'">Remover pergunta</button></div>').join('');$$('[data-rem-pergunta]').forEach(bt=>bt.onclick=()=>{ler();i.questoes.splice(+bt.dataset.remPergunta,1);pintar();});};
  $('#eg-add-dim').onclick=()=>{ler();i.dimensoes.push({id:uuid(),titulo:'',forte:'',desenvolver:'',recomendacoes:[]});pintar();};$('#eg-add-pergunta').onclick=()=>{ler();i.questoes.push({id:uuid(),texto:'',dimensao:i.dimensoes[0].id,inversa:false});pintar();};pintar();
  $('#eg-instrumento').onsubmit=async ev=>{ev.preventDefault();ler();Object.assign(i,{duracaoMinutos:$('#ac-inst-duracao').value?Number($('#ac-inst-duracao').value):null,titulo:$('#ac-inst-titulo').value.trim(),versao:$('#ac-inst-versao').value.trim(),setor:$('#ac-inst-setor').value.trim(),objetivo:$('#ac-inst-objetivo').value.trim(),instrucoes:$('#ac-inst-instrucoes').value.trim(),metodologia:$('#ac-inst-metodo').value.trim(),autorizacao:$('#ac-inst-autorizacao').value.trim(),escala:$('#ac-inst-escala').value.split('\n').map(x=>x.trim()).filter(Boolean),liberacao:A().lerAudiencia(),visibilidade:Array.from($('#eg-consultores').selectedOptions).map(o=>o.value),publicada:$('#eg-inst-publicada').checked,ativa:$('#eg-inst-ativa').checked});const bt=ev.target.querySelector('button[type=submit]');bt.disabled=true;const r=await A().salvar('salvarInstrumento',{instrumento:i,expectedRevision:antigo?._serverRevision||0},()=>{location.hash='#/perfil';});if(!r)bt.disabled=false;};
 }
 return {render};
})();
