# -*- coding: utf-8 -*-
"""
POPs de Mercado e Vendas, Criação e Engenharia e Apoio e Gestão que estavam
sem procedimento escrito + as 2 jornadas que faltavam para fechar as linhas
(Embarque/Expedição e Instalação em campo).
"""

P  = lambda t: {"tipo": "paragrafo", "texto": t}
S  = lambda t: {"tipo": "subtitulo", "texto": t}
PS = lambda *i: {"tipo": "passos", "itens": list(i)}
L  = lambda *i: {"tipo": "lista", "itens": list(i)}
D  = lambda t: {"tipo": "destaque", "texto": t}
A  = lambda t: {"tipo": "alerta", "texto": t}
CK = lambda *i: {"tipo": "checklist", "itens": list(i)}

def pop(idn, codigo, setor, titulo, objetivo, resp, epis, blocos):
    return {"id": "pop-" + idn, "codigo": codigo, "setor": setor, "titulo": titulo,
            "objetivo": objetivo, "responsavel": resp, "epis": epis, "blocos": blocos,
            "versao": "1.0", "revisadoEm": "2026-08-04T12:00:00.000Z",
            "revisadoPor": "Semente inicial"}

def et(idn, titulo, blocos):
    return {"id": "et-" + idn, "titulo": titulo, "blocos": blocos}

POPS_APOIO = [

pop('mkt-01', 'POP-MKT-01', 'Marketing', 'Registro de obra e publicação de case',
    'Toda obra boa vira material de venda: foto certa, autorização do cliente e publicação que traz o próximo pedido.',
    'Marketing', [], [
    S('Quando se aplica'),
    L('Toda instalação concluída com resultado apresentável.',
      'Peças de destaque: fachada, letreiro luminoso, porta, envelopamento.'),
    S('A foto que vende (e a que não vende)'),
    L('Frontal, a 5–10 m, com a fachada inteira no quadro — é assim que o cliente vê da rua.',
      'Luminoso: foto ao ENTARDECER, com a luz acesa. Foto de luminoso apagado não vende luminoso.',
      'Antes e depois, do MESMO ângulo — é o par que mais converte.',
      'Sem carro na frente, sem lixo, sem escada aparecendo.',
      'Detalhe do acabamento em close: é ele que separa a Impresilk do concorrente barato.'),
    S('Passo a passo'),
    PS('Combinar com a equipe de instalação as fotos do checklist (POP-MONT-01) — elas já vêm da obra.',
       'Pedir a foto do LOCAL VAZIO antes: sem ela não existe "antes e depois".',
       'Confirmar com o Comercial se o cliente autoriza a divulgação (alguns não autorizam por contrato ou por marca).',
       'Selecionar as 3 a 5 melhores e tratar: enquadramento, horizonte no nível, cor fiel.',
       'Escrever o case: o problema do cliente, a solução aplicada, o material e o prazo.',
       'Publicar no Instagram e adicionar ao portfólio do site.',
       'Marcar o cliente quando ele autorizar — é o que gera indicação.',
       'Arquivar as fotos com o nº da O.S. para o portfólio e para futuras propostas.'),
    S('Pontos de atenção'),
    L('Publicar sem autorização → problema com o cliente e com a marca dele.',
      'Foto tirada de baixo, torta → a peça parece torta mesmo estando reta.',
      'Luminoso fotografado de dia → some o produto que se está vendendo.',
      'Case sem o "problema resolvido" → vira foto bonita, não argumento de venda.'),
    S('Checklist final'),
    CK('Autorização do cliente confirmada com o Comercial',
       'Foto frontal a 5–10 m',
       'Luminoso fotografado aceso, ao entardecer',
       'Par antes/depois do mesmo ângulo',
       'Texto do case com problema, solução, material e prazo',
       'Arquivado com o nº da O.S.'),
    S('Registro'),
    L('Pasta do case com o nº da O.S.', 'Data da publicação e autorização do cliente.')]),

pop('psv-01', 'POP-PSV-01', 'Pós-venda', 'Atendimento de garantia e manutenção de fachada',
    'Reclamação vira solução rápida e rastreável: causa identificada, responsabilidade clara e cliente informado em 24 h.',
    'Pós-venda', [], [
    S('Quando se aplica'),
    L('Peça com defeito dentro da garantia.',
      'Manutenção preventiva ou limpeza de fachada.',
      'Peça danificada por terceiros ou intempérie (fora de garantia, vira orçamento).'),
    S('Passo a passo'),
    PS('Registrar o chamado com: cliente, nº da O.S. original, data da instalação e o que está acontecendo.',
       'Pedir FOTO ao cliente antes de agendar — metade dos chamados se resolve por telefone.',
       'Responder em até 24 h, mesmo que seja para dizer "vamos até aí na terça".',
       'Consultar a O.S. original: material, fixação usada, quem instalou e o registro fotográfico.',
       'Classificar a causa: defeito de fabricação · falha de instalação · uso indevido · intempérie/terceiro.',
       'Garantia (fabricação ou instalação) → agendar o reparo sem custo e informar a produção.',
       'Fora de garantia → orçar como serviço, explicando ao cliente por que não é garantia.',
       'Executar seguindo o POP de instalação, com o mesmo checklist fotográfico.',
       'Fechar o chamado com foto do reparo e confirmação do cliente.',
       'Devolver a causa raiz ao setor de origem — é isso que impede a repetição.'),
    S('Casos que mais aparecem'),
    L('LED apagado → quase sempre o cliente ligou direto na tomada, sem a fonte (ver POP-MONT-04).',
      'Adesivo descolando na borda → superfície suja na aplicação ou material vencido.',
      'Lona rasgada no ilhós → ilhós fora da bainha ou espaçamento largo demais.',
      'Fachada infiltrando → junta sem silicone neutro.'),
    S('Pontos de atenção'),
    L('Demorar a responder é pior que a falha em si.',
      'Prometer garantia sem consultar a O.S. → custo que não era nosso.',
      'Resolver e não avisar o setor de origem → o mesmo erro volta no mês seguinte.'),
    S('Checklist final'),
    CK('Chamado registrado com o nº da O.S. original',
       'Foto do cliente recebida antes do agendamento',
       'Resposta dada em até 24 h',
       'Causa classificada',
       'Reparo executado com checklist fotográfico',
       'Cliente confirmou',
       'Causa raiz devolvida ao setor de origem'),
    S('Registro'),
    L('Chamado com causa e desfecho.', 'Fotos antes e depois do reparo.')]),

pop('arf-01', 'POP-ARF-01', 'Arte-final e pré-impressão', 'Fechamento de arquivo e prancha de produção',
    'Arquivo que entra na máquina sem ajuste: medida final, cor no perfil certo, sangria e corte marcados — e a prancha que a fábrica lê.',
    'Arte-finalista', [], [
    S('Quando se aplica'),
    L('Toda arte aprovada pelo cliente que vai para produção.',
      'Geração de prancha de produção para os setores de fábrica.'),
    S('O que é "arquivo fechado"'),
    L('Medida FINAL da peça, na escala combinada (1:1 quando possível).',
      'Resolução adequada à distância de leitura (fachada não precisa da resolução de um adesivo).',
      'Fontes convertidas em curvas.',
      'Cor no perfil do material que será usado.',
      'Sangria e linha de corte/refile marcadas.',
      'Contorno de recorte em camada própria, vetores fechados.'),
    S('Passo a passo'),
    PS('Receber a arte aprovada e a O.S.; conferir se a aprovação é a versão FINAL.',
       'Conferir a medida contra a O.S. e contra a medição da visita — divergência volta ao Comercial.',
       'Converter cores para o perfil do material e sinalizar cor crítica da marca do cliente.',
       'Aplicar sangria e marcar corte/refile conforme o acabamento previsto.',
       'Preparar o recorte de contorno (quando houver) em camada separada.',
       'Fazer o nesting quando a peça for cortada em chapa, para aproveitar material.',
       'Gerar a PRANCHA DE PRODUÇÃO com: cliente, O.S., material, medidas, quantidade e observações da fábrica.',
       'Nomear o arquivo no padrão da casa (O.S. + cliente + peça + versão).',
       'Salvar na pasta de APROVADOS — só o que está lá pode ir para a máquina.',
       'Liberar para o setor de produção correspondente.'),
    S('Pontos de atenção'),
    L('Arte boa em 30 cm pode ser lixo em 3 m → conferir resolução na medida REAL.',
      'Fonte não convertida → a máquina troca a fonte e ninguém percebe até a peça pronta.',
      'Vetor aberto no recorte → contorno errado e peça perdida.',
      'Versão errada aplicada → pasta de aprovados separada resolve.',
      'Prancha sem observação da fábrica → o operador decide sozinho o que não é dele decidir.'),
    S('Checklist final'),
    CK('Medida final conferida contra a O.S.',
       'Resolução adequada à distância de leitura',
       'Fontes em curvas',
       'Perfil de cor do material aplicado; cor crítica sinalizada',
       'Sangria e corte marcados',
       'Contorno em camada própria, vetores fechados',
       'Prancha de produção gerada',
       'Arquivo na pasta de aprovados, nomeado no padrão'),
    S('Registro'),
    L('Prancha de produção anexada à O.S.', 'Versão do arquivo aprovado.')]),

pop('prj-01', 'POP-PRJ-01', 'Projetos técnicos', 'Projeto de estrutura e memorial',
    'Estrutura dimensionada para o vento e para o peso reais do local, com fixação definida e memorial que a fábrica e o instalador conseguem executar.',
    'Projetista', [], [
    S('Quando se aplica'),
    L('Fachadas, letreiros com estrutura, totens, portas e revestimentos.',
      'Qualquer peça acima de 3 m de altura ou com peso relevante.'),
    S('O que o projeto precisa definir'),
    L('Medidas finais e a estrutura (bitola do metalon, chapa, perfil).',
      'Fixação: tipo de superfície, fixador, quantidade e espaçamento.',
      'Peso total e o ponto de apoio.',
      'Se leva iluminação: posição do LED, da fonte e o caminho do fio.',
      'Acabamento: cor e onde é pintado.'),
    S('Passo a passo'),
    PS('Conferir a medição da visita (Brief) e as fotos do local.',
       'Identificar a superfície de fixação — alvenaria, drywall, vidro, ACM, cerâmica, telha, madeira.',
       'Dimensionar a estrutura pelo VÃO e pelo peso, não pelo que sobrou no estoque.',
       'Definir a fixação compatível com a superfície e com o peso, com folga de segurança.',
       'Prever dilatação e drenagem em peça externa (metal esquenta; água entra).',
       'Desenhar o corte do metalon e o plano de solda para a Metalurgia.',
       'Gerar o memorial: lista de material, sequência de montagem e sequência de instalação.',
       'Submeter ao PCP para aprovação antes de liberar para a fábrica.',
       'Liberar para a Metalurgia/Corte com o projeto aprovado anexado à O.S.'),
    S('Pontos de atenção'),
    L('Projetar sem foto do local → surpresa na instalação.',
      'Ignorar o vento em fachada alta → estrutura que trabalha e solda que trinca.',
      'Fixação escolhida no papel sem confirmar a superfície → equipe furando e improvisando na obra.',
      'Peça externa sem dreno → água acumulada e ferrugem por dentro.',
      'Memorial sem sequência → a fábrica monta na ordem errada e desmonta para corrigir.'),
    S('Checklist final'),
    CK('Medição e fotos do local conferidas',
       'Superfície de fixação identificada',
       'Estrutura dimensionada para peso e vento',
       'Fixação definida com quantidade e espaçamento',
       'Dilatação e drenagem previstas',
       'Memorial com material e sequência',
       'Aprovado pelo PCP antes de liberar'),
    S('Registro'),
    L('Projeto e memorial anexados à O.S.', 'Aprovação do PCP registrada.')]),

pop('rh-01', 'POP-RH-01', 'RH e DP', 'Integração de novo colaborador',
    'Pessoa nova produzindo com segurança na primeira semana: documentos em ordem, EPI na mão, acessos criados e POPs do setor lidos.',
    'RH e DP', [], [
    S('Quando se aplica'),
    L('Toda contratação, inclusive temporária e de experiência.'),
    S('Passo a passo — antes do primeiro dia'),
    PS('Fechar a documentação e o registro em folha.',
       'Separar os EPIs do setor e a ficha de entrega de EPI (NR-06).',
       'Pedir ao TI a criação dos acessos aos sistemas que a função exige.',
       'Avisar o gestor do setor e definir quem será o padrinho da pessoa.'),
    S('Primeiro dia'),
    PS('Apresentar a empresa: o que a Impresilk faz, as 4 linhas de produção e onde a função dela entra.',
       'Entregar os EPIs contra assinatura e explicar o uso de cada um.',
       'Treinar segurança do setor: máquinas, riscos e o que NÃO se faz.',
       'Apresentar aos setores vizinhos — de quem recebe e para quem entrega.',
       'Criar o acesso ao Pops & Fabricação e mostrar como consultar os POPs na bancada.'),
    S('Primeira semana'),
    PS('Definir os POPs obrigatórios do setor e acompanhar a leitura no mapa de treinamento.',
       'Iniciar a jornada de fabricação da função (Corte, Metalurgia, Pintura, Montagem, Impressão, Acabamento ou Brindes).',
       'Acompanhamento diário do padrinho.',
       'Ao fim da semana: conversa de alinhamento com o gestor.'),
    S('Pontos de atenção'),
    L('Pessoa em máquina sem treinamento de segurança → acidente e responsabilidade da empresa.',
      'EPI entregue sem assinatura → não existe comprovação legal.',
      'Acesso criado depois → a pessoa passa a semana pedindo favor para os outros.',
      'Sem padrinho definido → aprende errado com quem estiver por perto.'),
    S('Checklist final'),
    CK('Documentação e registro concluídos',
       'EPIs entregues com ficha assinada (NR-06)',
       'Treinamento de segurança do setor realizado',
       'Acessos criados (inclusive Pops & Fabricação)',
       'POPs obrigatórios do setor lidos e registrados',
       'Jornada de fabricação da função iniciada',
       'Conversa de alinhamento na primeira semana'),
    S('Registro'),
    L('Ficha de entrega de EPI assinada.',
      'Mapa de treinamento do Pops & Fabricação (leituras e jornadas).')]),

pop('ti-01', 'POP-TI-01', 'TI e sistemas', 'Criação e remoção de acesso aos sistemas',
    'Quem entra tem acesso no primeiro dia; quem sai perde no mesmo dia. Sempre pela Central, sempre com registro.',
    'TI e sistemas', [], [
    S('Quando se aplica'),
    L('Contratação, mudança de função e desligamento.',
      'Pedido de acesso a um sistema novo.'),
    S('Os sistemas da casa'),
    L('Painel de Gestão · RH (Pessoas) · PCP/Instalação · Brief de Medição · DRE Caixa · Compras · Pops & Fabricação.',
      'Todos com login pela CENTRAL DE ACESSOS — uma conta por pessoa, mesma senha em todos.',
      'ERP Mubisys tem cadastro próprio, feito à parte.'),
    S('Passo a passo — criar'),
    PS('Receber do RH a função e os sistemas que ela exige.',
       'Criar a conta na Central de Acessos, com senha TEMPORÁRIA legível.',
       'Definir o papel em cada sistema (o menor possível para a função).',
       'Entregar usuário e senha à pessoa por canal direto — a senha troca na primeira entrada.',
       'Confirmar que a pessoa conseguiu entrar e trocar a senha.'),
    S('Passo a passo — remover'),
    PS('Receber o aviso de desligamento do RH no MESMO dia.',
       'Desativar a conta em TODOS os sistemas pela Central.',
       'Conferir no histórico de acessos se houve entrada depois do desligamento.',
       'Recolher aparelho da empresa e sair da conta nele ("Sair e limpar" no Brief).',
       'Trocar senhas compartilhadas que a pessoa conhecia (a porta do DRE é de todos).'),
    S('Pontos de atenção'),
    L('Conta compartilhada entre duas pessoas → o histórico deixa de dizer quem fez o quê.',
      'Papel maior que a função → alguém apaga o que não devia.',
      'Desligamento sem desativar → acesso ativo por 30 dias (o crachá dura isso).',
      'Senha mandada em grupo → deixa de ser senha.'),
    S('Checklist final'),
    CK('Conta criada na Central, com senha temporária',
       'Papel mínimo necessário para a função',
       'Pessoa entrou e trocou a senha',
       'No desligamento: desativada em todos os sistemas no mesmo dia',
       'Histórico conferido',
       'Senhas compartilhadas trocadas'),
    S('Registro'),
    L('Histórico de acessos da Central (quem criou, quem removeu e quando).')]),

pop('mnt-01', 'POP-MNT-01', 'Manutenção', 'Manutenção preventiva das máquinas críticas',
    'Laser fibra, CO2, router e UV rodando — porque máquina parada nessas quatro para uma linha inteira de produção.',
    'Manutenção', ['Óculos de proteção', 'Luva'], [
    D('Prioridade 1 da manutenção: laser fibra, laser CO2, router CNC e impressora UV. Se uma delas para, uma linha inteira para junto.'),
    S('Quando se aplica'),
    L('Rotina preventiva (diária, semanal e mensal).',
      'Qualquer sintoma de perda de qualidade antes de virar quebra.'),
    S('Rotina diária (o operador faz)'),
    L('Limpar a mesa e remover resíduo de corte.',
      'Conferir nível de refrigeração e ar comprimido.',
      'Limpar lente e conferir bico (laser).',
      'Conferir fresa e pinça (router).',
      'Impressora UV: limpeza de cabeçote e teste de bicos ANTES do primeiro trabalho.'),
    S('Rotina semanal'),
    L('Lubrificar guias e fusos conforme o manual.',
      'Conferir e limpar filtros da exaustão.',
      'Conferir folga de eixo (peça saindo fora de medida costuma ser folga, não arquivo).',
      'Drenar o compressor — água no ar arruína pintura e corte.'),
    S('Rotina mensal'),
    L('Conferir alinhamento e potência do laser.',
      'Conferir correias e rolamentos.',
      'Revisar sistema de tinta da UV e limpeza profunda de cabeçote.',
      'Testar botões de emergência de TODAS as máquinas.'),
    S('Passo a passo do chamado'),
    PS('Registrar o sintoma com a máquina, o horário e o que estava sendo feito.',
       'Avisar o PCP na hora — é ele que remaneja a produção.',
       'Diagnosticar do simples para o complexo (consumível → ajuste → mecânica → eletrônica).',
       'Executar o reparo ou acionar a assistência, com o custo aprovado pela direção.',
       'Registrar o que foi feito e a peça trocada.',
       'Rodar uma peça de teste e liberar a máquina formalmente.'),
    S('Pontos de atenção'),
    L('Perda de qualidade é aviso de quebra: borda ruim, faixa na impressão e medida fora costumam vir antes da parada.',
      'Manutenção adiada sempre volta mais cara e no pior dia.',
      'Máquina liberada sem peça de teste → o problema aparece na peça do cliente.',
      'Botão de emergência que ninguém testa é decoração.'),
    S('Checklist final'),
    CK('Rotina diária cumprida nas 4 máquinas críticas',
       'Semanal e mensal em dia',
       'Chamados registrados com sintoma e solução',
       'Peça de teste rodada antes de liberar',
       'PCP informado de parada e de retorno'),
    S('Registro'),
    L('Ficha de manutenção por máquina (data, serviço, peça trocada).',
      'Histórico de paradas — é ele que mostra qual máquina precisa de investimento.')]),
]

# ── as 2 jornadas que faltavam para fechar as 4 linhas ──────────────────────
JORNADAS_FECHAMENTO = [

{"id": "jor-expedicao", "titulo": "Embarque e expedição", "ordem": 9,
 "nivel": "Introdutório", "versao": "1.0", "linha": "linha-letras", "setor": "PCP e Expedição",
 "descricao": "A peça sai inteira e completa: conferência contra a O.S., embalagem que protege e carga que chega sem avaria.",
 "revisadoEm": "2026-08-04T12:00:00.000Z",
 "etapas": [
  et('exp-1', 'A última chance de pegar o erro', [
    P('A expedição é o último setor a ver a peça antes do cliente. Tudo que passar daqui vira viagem perdida, equipe parada na obra e reclamação — e nada disso volta.'),
    D('A pergunta da expedição não é "está pronto?". É: se eu fosse instalar isso amanhã, com essa caixa, chegaria tudo que eu preciso? Se falta um parafuso, a obra para.'),
    S('O que se confere aqui'),
    L('Quantidade e medidas contra a O.S.',
      'Kit completo: fixadores, buchas, espaçadores, fonte, chaves e gabarito.',
      'Peça sem avaria e com a proteção no lugar.',
      'Identificação: nº da O.S. em toda embalagem.')]),
  et('exp-2', 'Conferência e embalagem', [
    PS('Conferir a O.S. item a item — não pelo volume aparente.',
       'Conferir se a peça foi testada onde há teste (letra acesa, porta abrindo).',
       'Embalar por tipo: letras individualmente com papelão entre elas; ACM em pé com proteção em todas as faces; lona dobrada com a arte para DENTRO.',
       'Colocar o kit de fixação junto da peça, identificado.',
       'Incluir o gabarito 1:1 quando houver conjunto de letras.',
       'Etiquetar cada volume com o nº da O.S., o cliente e "volume X de Y".'),
    A('Peça sem "volume X de Y" é peça que se perde: a equipe leva 2 volumes de 3 e descobre na obra.')]),
  et('exp-3', 'Carga, rota e entrega', [
    PS('Conferir o veículo: espaço, carga amarrada e nada apoiado sobre a face de vista.',
       'ACM e acrílico viajam EM PÉ, nunca deitados uns sobre os outros.',
       'Peça luminosa: fonte e cabos em caixa separada e identificada.',
       'Conferir a rota e o horário combinado com o cliente.',
       'Registrar a saída (o que saiu, para onde e com quem).',
       'Na entrega, conferir com quem recebe e colher o aceite.'),
    S('Erros que a gente não repete'),
    L('Carregar sem conferir a O.S. → falta peça na obra.',
      'ACM deitado com peso em cima → risco e amassado.',
      'Kit de fixação esquecido → equipe improvisa e a peça cai depois.',
      'Sem registro de saída → ninguém sabe o que foi entregue.'),
    CK('O.S. conferida item a item', 'Kit de fixação junto e identificado',
       'Gabarito incluído (conjunto de letras)', 'Volumes etiquetados X de Y',
       'Carga amarrada, ACM em pé', 'Saída registrada')]),
 ]},

{"id": "jor-instalacao", "titulo": "Instalação em campo", "ordem": 10,
 "nivel": "Avançado", "versao": "1.0", "linha": "linha-letras", "setor": "Instalação de placas",
 "descricao": "Trabalho em altura com NR-35, vistoria antes de furar e checklist fotográfico: a etapa onde o erro é caro e o risco é real.",
 "revisadoEm": "2026-08-04T12:00:00.000Z",
 "etapas": [
  et('ins-1', 'Segurança em altura não é burocracia', [
    A('Acima de 2 m já é trabalho em altura (NR-35). Cinto de segurança com talabarte ancorado em ponto firme, capacete com jugular e treinamento válido. Quem não tem o treinamento NÃO sobe — não é rigor, é a diferença entre voltar para casa e não voltar.'),
    S('Antes de subir'),
    L('Andaime montado e travado, ou escada amarrada e no ângulo certo.',
      'Ponto de ancoragem conferido — estrutura que segura pessoa, não calha.',
      'Área isolada embaixo: ferramenta que cai de 6 m mata.',
      'Ninguém trabalha sozinho em altura.',
      'Chuva, vento forte ou trovoada: para. A peça espera; a pessoa não se repõe.'),
    D('A régua da equipe: se alguém não está confortável em subir naquelas condições, a instalação é adiada e o gerente é acionado. Nunca se resolve isso na pressão do dia.')]),
  et('ins-2', 'Vistoria: o que se descobre antes de furar', [
    PS('Conferir a superfície REAL contra o projeto — alvenaria, drywall, vidro, ACM, cerâmica, telha.',
       'Conferir as medidas do local com trena, contra o projeto.',
       'Procurar fiação, tubulação e obstáculo oculto antes de escolher o ponto.',
       'Confirmar o ponto elétrico quando a peça é luminosa (e o que o pedido cobre).',
       'Divergência de qualquer tipo → parar e acionar o gerente. Nunca improvisar fixação.'),
    P('Esta etapa é curta e evita o retrabalho mais caro da empresa: a peça furada no lugar errado.')]),
  et('ins-3', 'Execução e registro', [
    PS('Marcar os pontos com trena e nível ANTES de furar.',
       'Conferir de longe (5–10 m) com a peça apoiada, antes da fixação definitiva.',
       'Fixar com o fixador correto para a superfície identificada.',
       'Peça luminosa: ligar na FONTE, nunca direto na rede; testar acesa antes de descer.',
       'Vedar passagem de fio e juntas com silicone neutro.',
       'Limpar o local e deixar como encontrado.',
       'Registro obrigatório: foto do local vazio (antes), foto do resultado (depois), relato no grupo com o nº da O.S. e aceite do cliente.'),
    S('Entrega ao cliente'),
    L('Mostrar a fonte e avisar que ligar direto na tomada queima os LEDs (a garantia não cobre).',
      'Explicar a manutenção simples: limpeza com pano úmido, sem solvente.',
      'Registrar a orientação no relato da O.S.'),
    CK('Treinamento NR-35 válido de quem subiu',
       'Ancoragem e isolamento da área conferidos',
       'Vistoria feita antes de furar',
       'Nível conferido antes e depois',
       'Peça luminosa testada ACESA no local',
       'Vedação feita',
       'Foto antes + foto depois + relato com a O.S. + aceite do cliente')]),
 ]},
]
