# -*- coding: utf-8 -*-
"""
POPs dos setores de OPERAÇÕES que estavam sem procedimento escrito.
Formato: modelo institucional Impresilk 2026 (objetivo · quando se aplica ·
materiais · passo a passo · pontos de atenção · checklist · registro).
"""

P  = lambda t: {"tipo": "paragrafo", "texto": t}
S  = lambda t: {"tipo": "subtitulo", "texto": t}
PS = lambda *i: {"tipo": "passos", "itens": list(i)}
L  = lambda *i: {"tipo": "lista", "itens": list(i)}
D  = lambda t: {"tipo": "destaque", "texto": t}
A  = lambda t: {"tipo": "alerta", "texto": t}
CK = lambda *i: {"tipo": "checklist", "itens": list(i)}

def pop(idn, codigo, setor, titulo, objetivo, resp, epis, blocos):
    return {"id": "pop-" + idn, "codigo": codigo, "setor": setor, "titulo": titulo,
            "objetivo": objetivo, "responsavel": resp, "epis": epis, "blocos": blocos,
            "versao": "1.0", "revisadoEm": "2026-08-04T12:00:00.000Z",
            "revisadoPor": "Semente inicial"}

POPS_OPERACOES = [

pop('cmp-01', 'POP-CMP-01', 'Compras e almoxarifado', 'Compra de material e entrada no estoque',
    'Material certo, na quantidade certa, antes de a produção parar — e com o custo lançado no centro certo.',
    'Comprador / Almoxarife', ['Luva (movimentação de chapa)', 'Sapato fechado'], [
    S('Quando se aplica'),
    L('Pedido de material do PCP ou de qualquer setor de produção.',
      'Reposição de item de giro que bateu no mínimo.',
      'Compra específica de O.S. (material que não é de estoque).'),
    S('O que a Impresilk compra'),
    L('Chapas: ACM, acrílico, PVC expandido, poliondas, MDF.',
      'Impressos: vinil adesivo, lona, laminação, ribbon.',
      'Perfis de alumínio, metalon, chapa de aço e inox.',
      'LED, fontes, cabos e ferragens.',
      'Consumíveis: fresa, lâmina, bico, gás, tinta, cola, fita, rebite, bucha.'),
    S('Passo a passo'),
    PS('Receber a solicitação com: material, especificação (espessura, cor, marca), quantidade e a O.S. (quando for de pedido).',
       'Conferir o ESTOQUE antes de cotar — comprar o que já tem é dinheiro parado duas vezes.',
       'Cotar com no mínimo 2 fornecedores para item acima do valor definido pela direção; abaixo disso, fornecedor homologado direto.',
       'Comparar preço, PRAZO e frete juntos: o mais barato que chega depois da entrega não é o mais barato.',
       'Emitir a ordem de compra e registrar no Mubisys, com a O.S. quando for material de pedido.',
       'Informar ao PCP a data prometida de chegada — é ela que sustenta o prazo do cliente.',
       'No recebimento: conferir nota × pedido × material FÍSICO (espessura e cor se confere na chapa, não no papel).',
       'Recusar o que veio errado ou danificado NA HORA, com foto, antes de assinar o canhoto.',
       'Dar entrada no estoque e guardar no lugar certo, com a face de vista protegida.',
       'Encaminhar a nota ao Financeiro para o lançamento no centro de custo.'),
    S('Pontos de atenção'),
    L('Chapa de ACM e acrílico riscam no descarregamento → sempre em pé, nunca arrastada.',
      'Espessura vem errada com frequência → medir com paquímetro, não confiar na etiqueta.',
      'Vinil e lona têm lote: mesma cor em lotes diferentes pode variar → em peça grande, exigir lote único.',
      'Consumível esquecido (fresa, bico, lâmina) para a máquina inteira → tratar como item crítico de estoque.',
      'Comprar sem informar o PCP → o prazo do cliente é prometido no escuro.'),
    S('Checklist final'),
    CK('Estoque conferido antes de cotar',
       'Cotação com prazo e frete comparados',
       'Ordem registrada no Mubisys com a O.S.',
       'PCP informado da data de chegada',
       'Recebimento conferido no físico (medida, cor, quantidade, avaria)',
       'Entrada dada e material guardado protegido',
       'Nota encaminhada ao Financeiro'),
    S('Registro'),
    L('Ordem de compra no Mubisys.', 'Foto de avaria, quando houver recusa.',
      'Entrada de estoque com o nº da O.S., quando for de pedido.')]),

pop('imp-01', 'POP-IMP-01', 'Impressão digital e recorte', 'Impressão, recorte e liberação da peça',
    'Toda peça impressa sai na cor combinada, na medida final da O.S. e pronta para o acabamento — sem retrabalho de material.',
    'Operador de impressão', ['Luva (manuseio de vinil e lona)', 'Máscara (troca de tinta solvente)'], [
    S('Quando se aplica'),
    L('Qualquer peça em vinil adesivo, lona ou chapa rígida impressa.',
      'Recorte de vinil de cor (sem impressão) e recorte de contorno.'),
    S('Materiais e equipamentos'),
    L('Ampla e MyPrint (rolo, solvente/eco-solvente): lona e vinil.',
      'Impressora UV: impressão direta em chapa rígida.',
      'Plotter de recorte: contorno e vinil de cor.',
      'Consumíveis: tinta, lâmina, fita de transporte, álcool isopropílico.'),
    S('Passo a passo'),
    PS('Receber o arquivo liberado pela arte-final com a prancha de produção.',
       'Conferir arquivo × O.S.: medida FINAL, quantidade, material e onde a peça vai ser aplicada.',
       'Conferir o material em máquina: tipo, largura, lote e face de impressão.',
       'Enviar pelo RIP com o PERFIL DO MATERIAL (nunca o perfil genérico).',
       'Rodar tira de teste: cor, nitidez e ausência de faixas.',
       'Comparar cor crítica com a referência FÍSICA do cliente, na luz do dia.',
       'Imprimir o lote acompanhando as primeiras passadas.',
       'Respeitar a secagem/cura antes de enrolar ou empilhar.',
       'Recorte: conferir marca de registro, regular pressão e cortar o vinil SEM cortar o liner.',
       'Descascar e aplicar fita de transporte quando a peça for aplicada inteira.',
       'Conferir medida final com trena e liberar para o acabamento ou expedição.'),
    S('Pontos de atenção'),
    L('Faixas claras (banding) → bico entupido ou avanço desregulado; parar e limpar.',
      'Cor fora → perfil errado, material fora do perfilado ou tinta acabando.',
      'Peça enrolada úmida → transfere tinta para o verso e perde a peça.',
      'Recorte cortando o liner → o vinil rasga na aplicação.',
      'Aprovar cor na tela → monitor mente; só vale a comparação física.'),
    S('Checklist final'),
    CK('Arquivo confere com a O.S. (medida final e quantidade)',
       'Perfil de cor do material aplicado',
       'Tira de teste aprovada antes do lote',
       'Cor crítica comparada com referência física',
       'Sem banding, borrado ou marca de roda',
       'Recorte alinhado com a impressão',
       'Peça seca antes de enrolar, identificada com a O.S.'),
    S('Registro'),
    L('Consumo de material por O.S. (metros de lona/vinil).',
      'Foto da peça impressa quando a cor for crítica.')]),

pop('dtf-01', 'POP-DTF-01', 'DTF UV e brindes', 'Aplicação em brindes: DTF UV e gravação',
    'Brinde entregue com a marca aplicada no mesmo lugar em todas as peças, sem descolar e na quantidade exata do pedido.',
    'Operador de brindes', ['Óculos de proteção (laser)', 'Luva'], [
    S('Quando se aplica'),
    L('Aplicação de marca em copo, garrafa, caneca, caneta, chaveiro e afins.',
      'Gravação a laser em metal, madeira, couro e acrílico.'),
    S('Escolha da técnica'),
    L('Logo colorido, degradê ou foto → DTF UV.',
      'Peça premium, marca discreta e permanente → gravação a laser.',
      'Objeto escuro com DTF → precisa de branco de apoio, senão a cor some.'),
    S('Passo a passo'),
    PS('Conferir o pedido: quantidade, objeto, cor do objeto e arte.',
       'Conferir a arte no tamanho REAL da peça — logo pequeno demais some em caneta.',
       'Fazer UMA peça-piloto completa e conferir com a O.S.',
       'Na primeira vez com aquele cliente ou objeto, aprovar a piloto antes do lote.',
       'Limpar o objeto com álcool isopropílico (gordura de mão é a causa nº 1 de adesivo que descola).',
       'Posicionar com gabarito — nunca no olho: peça torta é a reclamação mais comum de brinde.',
       'Aplicar (DTF) pressionando do centro para as bordas, ou gravar (laser) com o foco ajustado à curva.',
       'Conferir por amostragem a cada bandeja.',
       'Separar as peças com defeito NA HORA.',
       'Contar o lote antes de embalar e proteger a área aplicada.'),
    S('Pontos de atenção'),
    L('Copo ou garrafa com verniz solto NÃO segura adesivo → testar uma peça do lote antes de aplicar em centenas.',
      'Plástico com cloro NÃO entra no laser (mesma regra do PVC).',
      'Objeto redondo precisa de rotativo ou berço, senão a marca sai torta e sem foco.',
      'Madeira gravada com potência demais solta fuligem que suja a mão do cliente.',
      'Contagem errada gera nova viagem: brinde se conta em unidade, sempre.'),
    S('Checklist final'),
    CK('Peça-piloto aprovada antes do lote',
       'Gabarito usado — posição igual em todas',
       'Objeto limpo com isopropílico antes da aplicação',
       'Amostragem conferida durante o lote',
       'Defeituosas separadas',
       'Contagem confere com a O.S.',
       'Embalagem protege a área aplicada'),
    S('Registro'),
    L('Foto da peça-piloto aprovada.', 'Quantidade produzida e refugo, por O.S.')]),

pop('cor-01', 'POP-COR-01', 'Corte de chapas e usinagem', 'Corte de chapas: seccionadora, router e laser CO2',
    'Peça cortada na medida do projeto, com a face de vista intacta e o melhor aproveitamento possível da chapa.',
    'Operador de corte', ['Óculos de proteção', 'Protetor auricular', 'Luva (manuseio de chapa)'], [
    S('Quando se aplica'),
    L('Corte de ACM, PVC expandido, acrílico, MDF e poliondas.',
      'Usinagem de contorno, furo e rebaixo para letras, portas e placas.'),
    S('Qual máquina para quê'),
    L('Seccionadora — corte reto em chapa grande; dá o esquadro base.',
      'Router CNC — contorno, curva, furo interno, rebaixo. É a máquina da letra e da porta.',
      'Laser CO2 — acrílico com borda polida, sem lixar.'),
    A('PVC NUNCA entra no laser: libera cloro, corrói a máquina e faz mal a quem respira. Na dúvida entre PVC e acrílico, pergunte ao almoxarifado ANTES de ligar.'),
    S('Passo a passo'),
    PS('Conferir arquivo × O.S.: medida final, quantidade e material.',
       'Conferir se os vetores estão fechados (contorno aberto vira peça perdida).',
       'Conferir a chapa: espessura com paquímetro, sem empeno, sem risco na face de vista.',
       'Montar o plano de corte aproveitando a chapa (nesting).',
       'Marcar qual é a face de vista — a proteção dela só sai no fim.',
       'Conferir fresa/lâmina/lente: fresa cega queima a borda; lente suja tira potência.',
       'Cortar UMA peça e conferir a medida ANTES do lote inteiro.',
       'Acompanhar o corte — nunca deixar a máquina sozinha.',
       'Rebarbar e identificar cada peça com o nº da O.S. e a posição.',
       'Separar por destino: Metalurgia, Pintura ou célula de Portas.',
       'Guardar o retalho aproveitável com a medida escrita.'),
    S('Pontos de atenção'),
    L('Cortar o lote sem conferir a primeira peça → chapa inteira perdida.',
      'Tirar o filme de proteção no corte → peça riscada.',
      'Peça sem identificação → montagem parada adivinhando.',
      'Retalho no chão → compra de chapa que não precisava.',
      'Avanço errado no router: derrete PVC, descola o ACM e queima o acrílico.'),
    S('Checklist final'),
    CK('Primeira peça conferida contra a O.S.',
       'Face de vista com proteção intacta',
       'Todas as peças rebarbadas',
       'Peças identificadas com O.S. e posição',
       'Retalho guardado e medido',
       'Consumo de chapa registrado'),
    S('Registro'),
    L('Consumo de chapa por O.S.', 'Retalho gerado, com medida.')]),

pop('pin-01', 'POP-PIN-01', 'Pintura', 'Pintura de peças de produção',
    'Peça pintada na cor exata do projeto, com aderência que resiste a sol e chuva, e curada antes de seguir.',
    'Pintor', ['Máscara com filtro para vapores orgânicos', 'Luva nitrílica', 'Óculos', 'Avental'], [
    A('A máscara da pintura é a de VAPORES ORGÂNICOS (carvão ativado) — a máscara de poeira não protege de solvente. Pintar sem ela é intoxicação lenta.'),
    S('Quando se aplica'),
    L('Peças vindas da Metalurgia e do Corte, antes da Montagem.',
      'Estruturas, quadros de porta, letras e suportes.'),
    S('Materiais'),
    L('Desengraxante, lixas (220/320/400/600), thinner e álcool isopropílico.',
      'Primer conforme o material: antiferrugem (ferroso), aderência (galvanizado/alumínio/PVC), selador (MDF).',
      'Tinta PU bicomponente (padrão para peça externa), esmalte sintético, verniz PU.',
      'Pistola, compressor com filtro de água, papelão de teste.'),
    S('Passo a passo'),
    PS('Conferir a peça contra a O.S.: quantidade e o CÓDIGO da cor (nunca "azul parecido").',
       'Desengraxar: pano limpo, nunca o da bancada.',
       'Lixar para dar ancoragem; selar borda de MDF; fosquear acrílico e PVC de leve.',
       'Remover TODO o pó (pano com thinner; soprar só espalha).',
       'Aplicar o primer do material e respeitar a cura antes de lixar.',
       'Testar aderência do primer: fita crepe forte num canto escondido — saiu primer, volte uma etapa.',
       'Misturar a tinta com o catalisador na proporção EXATA (copo graduado, não olhômetro) e coar.',
       'Regular a pistola no papelão e aplicar demãos FINAS e cruzadas, a 15–20 cm, perpendicular.',
       'Respeitar o intervalo entre demãos do fabricante.',
       'Deixar curar antes de manusear (24 h) e antes de adesivar (72 h no PU).',
       'Conferir sob luz rasante: poeira, dedo, escorrido.',
       'Anotar o código da cor na O.S. para retoque futuro.'),
    S('Pontos de atenção'),
    L('Superfície engordurada → a tinta abre "olho de peixe".',
      'Catalisador no olho → não cura ou trinca.',
      'Escorrido → NÃO passe o dedo; deixe secar, lixe 600 e retoque.',
      'Pintar com vento ou poeira → acabamento perdido.',
      'Adesivar antes da cura → o vinil arranca a tinta depois.',
      'MDF externo sem selar borda → incha na primeira chuva.'),
    S('Checklist final'),
    CK('Cor conferida pelo código da O.S., na luz do dia',
       'Sem marca de dedo, poeira ou escorrido sob luz rasante',
       'Topo e base pintados (as faces que mais pegam água)',
       'Cura respeitada antes de embalar/adesivar',
       'Código da cor anotado na O.S.'),
    S('Registro'),
    L('Código da cor por O.S.', 'Consumo de tinta e catalisador.')]),

pop('mtg-01', 'POP-MTG-01', 'Montagem de letras', 'Montagem de letra caixa e teste elétrico',
    'Letra montada com frente, corpo e LED no esquadro, testada ACESA, e embalada de forma que chegue inteira na obra.',
    'Montador', ['Luva limpa', 'Óculos de proteção'], [
    S('Quando se aplica'),
    L('Letra caixa cega e luminosa (frontal, halo ou lateral).',
      'Peças vindas do Corte, da Metalurgia e da Pintura.'),
    S('Passo a passo'),
    PS('Conferir as peças contra o projeto: quantidade, profundidade e cor.',
       'Conferir a numeração das peças — letra sem identificação vira quebra-cabeça.',
       'Montar corpo + frente mantendo profundidade IGUAL em todas as letras do conjunto (o olho percebe 2 mm na sombra).',
       'Peça luminosa: conferir o interior branco (é ele que rende a luz).',
       'Distribuir os módulos de LED respeitando a distância face–LED do projeto.',
       'Dimensionar a fonte com ~20% de folga e cabear em paralelo, respeitando a polaridade.',
       'Emendas soldadas e isoladas; furo de passagem do cabo com passa-fio vedado.',
       'Prever o dreno (furinho baixo) em letra externa — condensação mata LED.',
       'TESTE ELÉTRICO na bancada: energizar e conferir TODAS acesas, luz uniforme, sem mancha.',
       'Etiquetar: "LIGAR SOMENTE NA FONTE".',
       'Imprimir o gabarito 1:1 do conjunto e embalar as letras INDIVIDUALMENTE.'),
    S('Pontos de atenção'),
    L('LED colado sem teste → letra apagada na entrega e desmontagem no cliente.',
      'Fonte subdimensionada → luz fraca e fonte quente.',
      'Interior escuro em letra luminosa → luz morta.',
      'Sem dreno em letra externa → LED morto em 3 meses.',
      'Letras embaladas encostando → risco na face.',
      'Cola escorrida na face → aparece de noite, iluminada.'),
    S('Checklist final'),
    CK('Profundidade uniforme no conjunto',
       'Todas as letras testadas ACESAS (se luminosas)',
       'Fonte com folga de potência e acessível',
       'Etiqueta "ligar somente na fonte"',
       'Gabarito 1:1 impresso junto com a peça',
       'Fixadores, buchas e espaçadores no kit da O.S.',
       'Embalagem individual, com o nº da O.S.'),
    S('Registro'),
    L('Foto do conjunto ACESO na bancada, antes de embalar.',
      'Modelo e potência da fonte, na O.S.')]),

pop('por-01', 'POP-POR-01', 'Portas de ACM', 'Produção de porta de ACM: do corte à ferragem',
    'Porta no esquadro, com folga uniforme, que abre e fecha com um dedo — e continua assim daqui a dez anos.',
    'Montador de portas', ['Luva', 'Óculos de proteção', 'Protetor auricular'], [
    S('Quando se aplica'),
    L('Portas de ACM e revestimentos da linha Arquitetônica.'),
    S('Passo a passo'),
    PS('Medir o VÃO no local: largura em 3 alturas, altura nos 2 lados e as DIAGONAIS.',
       'Conferir prumo e nível do vão — vão torto muda o projeto da folha.',
       'Definir com o cliente o sentido de abertura e onde ficam dobradiça e fechadura.',
       'Cortar e dobrar conforme o projeto, mantendo a face de vista protegida.',
       'Montar o quadro na bancada plana, travado, e conferir as DIAGONAIS antes de fixar de vez.',
       'Reforçar internamente o ponto da fechadura.',
       'Fixar o fechamento do centro para as bordas, para não ondular.',
       'Instalar ferragens: dobradiças alinhadas no mesmo eixo; 3 dobradiças acima de ~20 kg.',
       'TESTE DE BANCADA: abrir e fechar 10 vezes ANTES da pintura.',
       'Enviar para a Pintura conforme o POP-PIN-01 (topo e base também).',
       'Remontar ferragens após a cura e testar todas as chaves.',
       'Embalar em pé, amarrada e protegida.'),
    S('Pontos de atenção'),
    L('Medida por telefone → folha que não entra no vão.',
      'Diagonais diferentes → porta que não fecha; resolver no projeto, não no improviso.',
      'Fechadura aberta depois da pintura → risco e retrabalho de pintura inteiro.',
      'Correr sem guia inferior → porta batendo com o vento na primeira semana.',
      'Entregar sem testar todas as chaves → assistência no dia seguinte.'),
    S('Checklist final'),
    CK('Diagonais iguais (±2 mm)',
       'Folgas uniformes ao redor da folha',
       'Reforço no ponto da fechadura',
       'Abre e fecha com um dedo, sem arrastar',
       'Todas as chaves testadas',
       'Topo e base pintados',
       'Kit completo: batente/trilho, ferragens, parafusos, buchas e chaves'),
    S('Registro'),
    L('Medidas do vão registradas na O.S.',
      'Foto da porta montada antes do transporte.')]),

pop('acb-01', 'POP-ACB-01', 'Acabamento', 'Acabamento de lona: bainha, emenda e ilhós',
    'Peça impressa que aguenta vento e chuva: bainha soldada, emenda invisível e ilhós que não arranca.',
    'Operador de acabamento', ['Luva (superfície quente)', 'Óculos'], [
    S('Quando se aplica'),
    L('Lona impressa (banner, fachada, testeira), faixas e telas.',
      'Refile de peças impressas e colocação de ilhós.'),
    S('Materiais'),
    L('Carrinho de soldar lona / máquina de solda, régua e estilete de refile.',
      'Ilhós, matriz e prensa; fita de reforço.'),
    S('Passo a passo'),
    PS('Conferir a medida FINAL da O.S. — a peça impressa vem com sobra de propósito.',
       'Refilar sobre superfície plana, com guia; corte torto aparece de longe.',
       'Marcar a dobra da bainha (3 a 5 cm, conforme o tamanho da peça).',
       'Testar temperatura e velocidade num RETALHO do mesmo material.',
       'Soldar a bainha e conferir puxando com a mão.',
       'Emenda: alinhar pela ARTE (o desenho continua), sobrepor 2 a 3 cm e soldar sem parar no meio.',
       'Conferir a emenda contra a luz — falha aparece como ponto claro.',
       'Reforçar as pontas da emenda e os cantos.',
       'Ilhós a cada 40–50 cm (menos em vento forte), SEMPRE na dupla camada da bainha.',
       'Conferir cada ilhós: nenhum girando ou solto.',
       'Dobrar com a arte para dentro e identificar com a O.S.'),
    S('Pontos de atenção'),
    L('Temperatura alta → queima a lona (amarela e quebradiça na dobra).',
      'Temperatura baixa → a solda abre depois, no cliente.',
      'Ilhós na lona simples → rasga no primeiro vento.',
      'Emenda alinhada pela borda em vez da arte → o desenho quebra.',
      'Peça dobrada com a arte para fora → risco na impressão.'),
    S('Checklist final'),
    CK('Medida final conferida com trena',
       'Bainha soldada em toda a volta, testada com a mão',
       'Emenda alinhada pela arte e sem falha contra a luz',
       'Ilhós na dupla camada, espaçamento uniforme',
       'Cantos reforçados',
       'Peça dobrada com a arte para dentro, identificada'),
    S('Registro'),
    L('Metragem acabada por O.S.', 'Quantidade de ilhós utilizada.')]),
]
